Select_first_checkbox = '//tbody/tr[1]/td[1]/div[1]/span[1]/label[1]'
Comment_Button = 'id=NC_ALARM_ONLY_ACTIVE_SYSTEM_ALARM_ACTION_ANNOTATION'
ID_APPLY_FILTER = 'id=DeviceAlarms_AppyFilterButton'
Header_Checkbox = 'id=headerCheckBox'
Comment_content = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[3]/textarea[1]'
comment_save = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[5]/div[1]/div[1]/button[1]/span[1]'
Alarm_ACK = 'id=NC_ALARM_ONLY_ACTIVE_SYSTEM_ALARM_ACTION_ACKNOWLEDGE'
Alarm_ACK_Comment = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[5]/textarea[1]'
Alarm_ACK_Confirm = 'id=NC_SYSTEM_ALARM_ACTION_ACKNOWLEDGE_Submit_Button'
Alarm_UnACK = 'id=NC_ALARM_ONLY_ACTIVE_SYSTEM_ALARM_ACTION_UNACKNOWLEDGE'
Alarm_UnACK_Comment = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[5]/textarea[1]'
Alarm_UnACK_Confirm = 'id=NC_SYSTEM_ALARM_ACTION_UNACKNOWLEDGE_Submit_Button'
Alarm_Clear = 'id=NC_ALARM_ONLY_ACTIVE_SYSTEM_ALARM_ACTION_CLEAR'
Alarm_Clear_Comment = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[5]/textarea[1]'
Alarm_Clear_Confirm = 'id=NC_SYSTEM_ALARM_ACTION_CLEAR_Submit_Button'
Alarm_Delete = 'id=NC_ALARM_ONLY_ACTIVE_SYSTEM_ALARM_ACTION_DELETE'
Alarm_Delete_Confirm = 'id=NC_SYSTEM_ALARM_ACTION_DELETE_Submit_Button'
#source = '//body[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[8]/input[1]'
#proable_cause_device = '//body[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[6]/input[1]'
#proable_cause_device='//*[@id="DC_DeviceAlarms_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[6]/div/input'
#Specific_problem ='//body[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[7]/input[1]'
#Proable_cause = '//body[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[6]/input[1]'
Specific_problem='//*[@id="NC_DeviceAlarms_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[7]/div/input'
Proable_cause='//*[@id="NC_DeviceAlarms_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[6]/div/input'
