Operator_Data_Menu = 'id=OperatorData'
OP_Service_setting = 'id=OperatorData_servicesetting'
OP_TacPool = 'id=OperatorData_tacpool'
OP_Zip= 'id=OperatorData_zip'
OP_CdmsLcib = 'id=OperatorData_cdmalcib'
OP_LteLcib = 'id=OperatorData_ltelcib'
OP_PN = 'id=OperatorData_pn'
OP_Mscid = 'id=OperatorData_mscid'
Service_package='id=servicepackage'
