# Timing source Page
XPATH_TIMING_SOURCE_HEADER_LABEL='//*[@id="DC_Timing Source_Header"]'
XPATH_LATITUDESIGN='//*[@id="DC_NominalGPS.LatitudeSign_ComboBox"]/input'
XPATH_LATITUDESIGN_COMBOBOX='//*[@id="DC_NominalGPS.LatitudeSign_ComboBox"]/div'
XAPTH_DEGREEOFLATITUDE='//*[@id="DC_NominalGPS.DegreesOfLatitude_TF"]'
XPATH_DEGREEOFLONGITUDE='//*[@id="DC_NominalGPS.DegreesOfLongitude_TF"]'
XPATH_DIRECTIONOFALTITUDE='//*[@id="DC_NominalGPS.DirectionOfAltitude_ComboBox"]'
XPATH_ALTITUDE='//*[@id="DC_NominalGPS.Altitude_TF"]'
XPATH_UNCERTAINTY_SEMI_MAJOR='//*[@id="DC_NominalGPS.UncertaintySemiMajor_TF"]'
XPATH_UNCERTAINTY_SEMI_MINOR='//*[@id="DC_NominalGPS.UncertaintySemiMinor_TF"]'
XPATH_UNCERTAINTY_ALTITUDE='//*[@id="DC_NominalGPS.UncertaintyAltitude_TF"]'
XPATH_ORIENTATION_MAJOR_AXIS='//*[@id="DC_NominalGPS.OrientationMajorAxis_TF"]'
XPATH_CONFIDENCE='//*[@id="DC_NominalGPS.Confidence_TF"]'

XPATH_Timing_DROPDOWN_LIST_NEXT_BUTTON = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]//span[contains(text(), "Save")]/parent::div'
#XPATH_ORP_SCALAR_PARAM_INPUT = '//*[contains(text(), "{section}")]//ancestor::div[1]//following-sibling::div//*[contains(text(), "{overridden_param}")]/parent::div//input'
XPATH_ORP_SCALAR_PARAM_INPUT = '//*[contains(text(),"GPS Configuration")]'
#XPATH_ORP_SCALAR_PARAM_INPUT = '//*[text(),"Nominal"]'
XPATH_TIMING_PARAM_SAVE_BUTTON = '//*[@id="DC_Timing_Source_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP = '//*[contains(text(),"Saved successfully")]'

GPS_TABLE='//*[@id="DC_Nominal GPS Configuration"]'
NTP_SERVER_BOX='//*[@id="DC_PTP.Source_ComboBox"]'
NTP_SERVER='//*[@id="DC_PTP.Source_ComboBox"]/input'
NTP_SERVER_COMBO='//*[@id="DC_PTP.Source_ComboBox"]/div'
NTP_TABLE='//*[@id="DC_Timing Source Configuration"]'


XPATH_OWP_DOWNLINK_CA_VALUE_TO_GET = '//input[@class="v-filterselect-input"]'
XPATH_NGPS_WEBGUI='//*[@id="ngps"]'
XPATH_LATITUDE_WEGUI='//*[@id="id_latitudeSign"]'
XPATH_DEGREE_OF_LATITUDE_WEBGUI='//*[@id="id_degreesOfLatitude"]'
XPATH_DEGREE_OF_LONGITUTE_WEBGUI='//*[@id="id_degreesOfLongitude"]'
XPATH_DIRECTION_OF_LATITUDE_WEBGUI='//*[@id="id_directionOfAltitude"]'
XPATH_ALTITUDE_WEBGUI='//*[@id="id_altitude"]'
XPATH_UNCERTAIN_ALTITUDE_WEBGUI='//*[@id="id_uncertaintyAltitude"]'
XPATH_UNCERTAIN_SEMI_MAJOR_WEBGUI='//*[@id="id_uncertaintySemiMajor"]'
XPATH_SEMI_MINOR_WEBGUI='//*[@id="id_uncertaintySemiMinor"]'
XPATH_ORIENTATION_MAJOR_WEBGUI='//*[@id="id_orientationOfMajorAxis"]'
XPATH_CONFIDENCE_WEBGUI='//*[@id="id_confidence"]'
XPATH_SAVE_BUTTON_ngps='//*[@id="nominalGpsFormSave"]'


XPATH_WEBGUI_HEADER='//*[@id="DC_WebGUI Overridden Params_Header"]'
XPATH_WEBGUI_OVERRIDDEN_TABLE='//*[@id="DC_WebGUI-Overridden_Table"]'
XPATH_OPERATIONAL_PARAM='//*[@id="DC_Operational Params_Header"]'
XPATH_OPERATIONAL_TABLE='//*[@id="DC_Nominal GPS Inuse"]'
XPATH_PROVISIONED_DATA='//*[@id="DC_Provisioned Data_Header"]'
XPATH_GPS_TABLE='//*[@id="DC_Nominal GPS Configuration"]'

XPATH_WHITELIST_BUTTON='//*[@id="whitelist"]'
XPATH_WHITELIST_ADD_BUTTON='//*[@id="add-whitelist"]'
XPATH_WHITELIST_ROW_ADD_SECTOR1='//*[@id="whitelist_table"]/tbody/tr[1]/td[2]/div/input'
XPATH_WHITELIST_ROW_ADD_SECTOR2='//*[@id="whitelist_table"]/tbody/tr[1]/td[3]/div/input'
XPATH_WHITELIST_SAVE='//*[@id="whitelistSave"]'
XPATH_WHITELIST_TABLE_CHECKBOX='//*[@id="whitelist_table"]/thead/tr/th[1]'
XPATH_DELETE_BUTTON_WEBUI='//*[@id="del-whitelist"]'

XPATH_DASHBOARD_HEADER='//*[@id="dashboardDiv"]'
XPATH_CANCEL_BUTTON='//*[@id="whitelistCancel"]'
XPATH_WHITELIST_OPERATIONAL_DATA='//*[@id="filterTable"]'
XPATh_SHOW_ADVANCE_OPTION='//*[@id="DC_WL_Link_Show_Advanced"]/div/div'
XPATH_WHITELIST_PROVISION_TABLE='//*[@id="DC_WhiteList RPs"]'

XPATH_INPUT_PRAM_WEBGUI='//*[@id="DC_WebGUI-Overridden_Table"]/div[2]/div/div/div[2]/input'
XPATH_WEBGUI_APPLY_FILTER='//*[@id="DC_NBIView_AppyFilterButton"]'
XPATH_WEBGUI_ELEMENT_DELETE='//*[@id="DC_WebGUI-Overridden_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[1]/div'
XPATH_DELETE_BUTTON='//*[@id="DC_RP_NBIView_DeleteFilterButton"]'
DELETE_CONFIRM_BUTTON='//*[@id="Annotation_Submit_Button"]'

XAPTH_EXPAND_COLLAPSE_BUTTON='//*[@id="DC_ExpandCollapse"]'
XPATH_SEARCH_TEXT='//*[@id="DC_Search_TextField"]'
XPATH_SERACH_INPUT_TEXT='//*[@id="DC__SearchComponent"]'
XPATH_DELETE_BUTTON_webgui_whiltelist='//*[@id="scalar-delete-layout"]'
XPATH_SAVE_BUTTON='//*[@id="DC_Device_Config_Save_Button"]'
XPATH_WHITELIST_TEXTBOX='//*[@id="DC_RUWhiteList_TF"]'

XPATH_NOMINAL_GPS_TABLE='//*[@id="DC_Nominal GPS Configuration"]'
XPATH_Latitudesign_webgui='//*[@id="DC_NominalGPS.LatitudeSign_TF"]'
XPATH_Direction_of_altitude_webgui='//*[@id="DC_NominalGPS.DirectionOfAltitude_TF"]'
ALTITUDE='//*[@id="DC_NominalGPS.Altitude_TF"]'
Uncertain_semi_major='//*[@id="DC_NominalGPS.UncertaintySemiMajor_TF"]'
uncertain_semi_minor='//*[@id="DC_NominalGPS.UncertaintySemiMinor_TF"]'
uncertain_altitude='//*[@id="DC_NominalGPS.UncertaintyAltitude_TF"]'
Confidence='//*[@id="DC_NominalGPS.Confidence_TF"]'


DELETE_LATITUDE_SIGN='//*[@id="NominalGPS.LatitudeSign"]//*[@id="scalar-delete-layout"]'
DELETE_DEGREE_OF_LATITUDE='//*[@id="NominalGPS.DegreesOfLatitude"]//*[@id="scalar-delete-layout"]'
DELETE_DEGREE_OF_LONGITUDE='//*[@id="NominalGPS.DegreesOfLongitude"]//*[@id="scalar-delete-layout"]'
DELETE_DIRECTION_OF_ALTITUDE='//*[@id="NominalGPS.DirectionOfAltitude"]//*[@id="scalar-delete-layout"]'
DELETE_ALTITUDE='//*[@id="NominalGPS.Altitude"]//*[@id="scalar-delete-layout"]'
DELETE_SEMI_MAJOR='//*[@id="NominalGPS.UncertaintySemiMajor"]//*[@id="scalar-delete-layout"]'
DELETE_SEMI_MINOR='//*[@id="NominalGPS.UncertaintySemiMinor"]//*[@id="scalar-delete-layout"]'
DELETE_UNCERTAIN_ALTITUDE='//*[@id="NominalGPS.UncertaintyAltitude"]//*[@id="scalar-delete-layout"]'
DELETE_ORIENTATION_MAJOR_AXIS='//*[@id="NominalGPS.OrientationMajorAxis"]//*[@id="scalar-delete-layout"]'
DELETE_CONFIDENCE='//*[@id="NominalGPS.Confidence"]//*[@id="scalar-delete-layout"]'

XPATH_WEBGUI_LINK='//*[@id="externLinkButton"]'