BULK_DEVICE_CONFIGURATION_URL = '{dms_device_console}#!dmsui-bulkDeviceConfiguration/?C0'
XPATH_BULK_DEVICE_CONFIGURATION_HEADER = '//*[contains(@class, "v-label-dms-featureLabel") and contains(text(), "Device Configuration")]'
XPATH_DEVICE_AND_SOFTWARE_INPUT = '//*[contains(text(), "{input}")]/parent::div/following::div//input'
XPATH_DEVICE_BULK_CONFIG_NEXT_BUTTON = '//button[span[text()="Next"]]'
XPATH_DEVICE_FILTER_LIST_INPUT = '//*[contains(@class, "deviceFilterList-ext")]/input'
XPATH_APPLY_FILTER_BUTTON = '//button[*[contains(text(), "Apply Filter")]]'
ID_SELECT_ALL_DEVICE_CHECKBOX_INPUT = 'id=headerCheckBoxPPJA'
ID_ADD_AVAILABLE_DEVICE_BUTTON = 'id=NC_Add_AvailableDevices_Btn'
XPATH_BULK_CONFIG_SAVE_BUTTON = '//button[span[text()="Save"]]'
ID_SELECTEDDEVICES_TEXT = '//*[@id="NC_Bulk_DeviceList_Disclosure"]/div[3]/div[5]/div/div/div[1]/div'


#XPATH_PATH_MACID_INPUT='//*[@id="NC_AvailablePPJDevice_Table"]/div[2]/div/div/div[2]/input'
XPATH_PATH_MACID_INPUT='//*[@id="NC_AvailablePPJDevice_Table"]/div[1]/div[1]/div/table/tbody/tr[2]/td[2]/div/input'
XPATH_APPLY_FILTER='//*[@id="ppj-apply-filter"]'
#XPATH_SELECT_DEVICE='//*[@id="NC_AvailablePPJDevice_Table"]/div[3]/div[1]/table/tbody/tr/td[1]/div'
XPATH_SELECT_DEVICE='//*[@id="NC_AvailablePPJDevice_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[1]/div'
XPATH_ADD_DEVICE_BUTTON='//*[@id="NC_Add_AvailableDevices_Btn"]'
#XPATH_DEVICE_LIST_TABLE='//*[@id="NC_Device_List_Table"]/div[3]/div[1]/table/tbody/tr/td[1]'
XPATH_DEVICE_LIST_TABLE='//*[@id="NC_Device_List_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[1]'
#Proactive job
XPATH_PROACTIVE_JOB_HEADER='//*[contains(@class, "v-label-dms-featureLabel") and contains(text(), "Proactive Job")]'
XPATH_ADD_JOB='//*[@id="NC_PProvisiong_ADDNew"]'
XAPTH_Job_Name='//*[@id="NC_PProvisiong_PPWindow_Name"]'
XPATH_JOB_STATE='//*[contains(@class, "v-radiobutton")]/label[contains(text(),"ENABLED")]'
#XPATH_JOB_STATE='//*[@id="NC_PProvisiong_PPWindow_JobState"]/span[1]'
XPATH_OPERATION_TYPE='//*[@id="NC_PProvisiong_PPWindow_OperationType"]/input'
XPATH_JOBTYPE='//*[@id="NC_PPJ_JobType"]/span[2]'
XPATH_DEVICE_TYPE_cntrl='//*[contains(text(), "Cntrl")]'
XPATH_DEVICE_CRITERIA_ALL='//*[@id="NC_PProvisiong_PPWindow_DeviceCriteria"]'
XAPTH_DEVICE_CRITERIA='//*[@id="NC_PProvisiong_PPWindow_DeviceCriteria"]/span[3]'
XPATH_PROACTIVE_SAVE='//*[@id="NC_Proactive_Save"]'

XPATH_Vertical_scroll='//*[@id="DC_Menu_Content_Get_Menu_Content_Page"]/div[2]/div/div[1]/div/div[3]/div'
XPATH_END_OF_PAGE='//*[@id="DC_Menu_Content_Get_Menu_Content_Page"]/div[2]/div/div[1]/div/div[3]/div/div[11]/div/div'
XPATH_BELOW_DEVICE='//*[@id="DC_Menu_Content_Get_Menu_Content_Page"]/div[2]/div/div[1]/div/div[3]/div'
XPATH_PAGE_END='//*[@id="DC_Menu_Content_Get_Menu_Content_Page"]/div[2]/div/div[1]/div/div[3]/div/div[11]/div'

XPATH_RF_PROVISION_TABLE='//*[@id="DC_RF Parameters Sector"]'

#XPATH_FILTER_NAME='//*[@id="NC_PProvisiong_FilterTable"]/div[2]/div/div/div[1]/input'
XPATH_FILTER_NAME='//*[@id="NC_PProvisiong_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[1]/div/input'
Proactive_job_Apply_Filter='//*[@id="NC_PProvisiong_ApplyFilter"]'
#XPATH_TABLE_ROW='//*[@id="NC_PProvisiong_FilterTable"]/div[3]/div[1]/table/tbody/tr/td[1]'
XPATH_TABLE_ROW='//*[@id="NC_PProvisiong_FilterTable"]/div[2]/div/table/tbody/tr/td[1]'
XPATH_DELETE_BUTTON_Proactive_Job='//*[@id="NC_ProProvisioning_Delete_Action_Button"]'
XPATH_CONFIRM_BUTTON_PROACTIVE_JOB='//*[@id="NC_PProvisiong_PPWindow_Confirm"]'
XPATH_Core_Network='//*[@id="DC_Core Network Parameter"]'
XPATH_SCHEDULE_JOBTYPE='//*[@id="NC_PPJ_JobType"]/span[1]'
XPATH_SCHEDULE_DATE='//*[@id="NC_PPJ_JobSchedule_StartDate"]/input'
XPATH_FREQUENCY='//*[@id="NC_PPJ_Frequency"]/input'
XPATH_OPERATION_TYPE_MODE='//*[contains(@class, "v-radiobutton")]/label[contains(text(),"Connection Request")]'

XPATH_OPERATION_HISTORY='//*[@id="DC_DMSHeader_Operation_History_Button"]'
#XPATH_OPERATION_HISTORY_TABLE_METHOD='//*[@id="DC_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[3]/div'
#XPATH_OPERATION_HISTORY_TABLE_METHOD='//*[@id="DMS_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[3]'
XPATH_OPERATION_HISTORY_TABLE_METHOD='//*[@id="DC_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[3]/div'
#XPATH_OPERATION_HISTORY_TABLE_RESOURCE_NAME='//*[@id="DC_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[4]/div'
#XPATH_OPERATION_HISTORY_TABLE_RESOURCE_NAME='//*[@id="DMS_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[4]'
XPATH_OPERATION_HISTORY_TABLE_RESOURCE_NAME='//*[@id="DC_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[4]/div/div'
#XPATH_OPERATION_HISTORY_TABLE_OPERATION_STATUS='//*[@id="DC_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[6]/div'
#XPATH_OPERATION_HISTORY_TABLE_OPERATION_STATUS='//*[@id="DMS_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[6]'
XPATH_OPERATION_HISTORY_TABLE_OPERATION_STATUS='//*[@id="DC_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[6]/div/div/div/div/div/div[1]'
XPATH_LAST_CONTACTED_TIME='//*[@id="DC_LastContactTime_Value_Label"]'
XPATH_RESULT_PANEL='//div[contains(@class,"Devicehistory")]'
XPATH_start_button='//*[@id="NC_PPJ_JobSchedule_StartDate"]/button'
XPATH_MINUTES_XPATH='//*[@id="PID_VAADIN_POPUPCAL"]/tbody/tr[3]/td/div/select[2]'

XPATH_OPERATION_APPLY_FILTER='//*[@id="applyFilter"]'
#XPATH_OPERATION_TABLE_INPUT='//*[@id="DMS_Operation_History_Table"]/div[2]/div/div/div[4]'
#XPATH_OPERATION_TABLE_INPUT='//*[@id="DC_Operation_History_Table"]/div[2]/div[1]/div/div[4]/input'
#XPATH_OPERATION_TABLE_INPUT='//*[@id="DMS_Operation_History_Table"]/div[1]/div[1]/div/table/tbody/tr[2]/td[4]/div/input'
XPATH_OPERATION_TABLE_INPUT='//*[@id="DC_Operation_History_Table"]/div[1]/div[1]/div/table/tbody/tr[2]/td[4]/div/input'
XPATH_START_TIME_bulk='//*[@id="NC_PPJ_JobSchedule_StartDate"]/input'