# Dashboard Page
ID_DASHBOARD_DASHBOARD_BUTTON = 'id=DC_Menu_Content_Dashboard_Button'
XPATH_DMS_INSERVICE_TAG = '//div[contains(@class,"dms-summary-inservice")]'
ID_DASHBOARD_LAST_CONTACT_TIME = 'id=DC_LastContactTime_Value_Label'
# XPATH_DASHBOARD_CONNECT_DEVICE = '//div[contains(@class,"v-csslayout-per-device-action-connect")]'
XPATH_DASHBOARD_CONNECT_DEVICE = '//div[@id="CONNECT"]'
# XPATH_DASHBOARD_REBOOT_DEVICE = '//div[contains(@class,"v-csslayout-per-device-action-reboot")]'
XPATH_DASHBOARD_REBOOT_DEVICE = '//div[@id="REBOOT"]'
# XPATH_DASHBOARD_REPLAN_DEVICE  = '//div[contains(@class,"v-csslayout-per-device-action-replan")]'
XPATH_DASHBOARD_REPLAN_DEVICE = '//div[@id="REPLAN"]'
ID_DASHBOARD_RESET_DEVICE = 'id=RESET'
ID_DASHBOARD_RESYNC_DEVICE = 'id=RESYNC'
ID_DASHBOARD_RESYNCALL_DEVICE = 'id=RESYNC_ALL'
ID_DASHBOARD_FIRMWARE_UPGRADE_BUTTON = 'id=FIRMWARE'
#XPATH_DASHBOARD_FIRMWARE_SELECT_UPGRADE_BUTTON = '//*[contains(text(), "5_5_firmware")]/parent::td/following-sibling::td[2]//div[contains(@id, "DC_FirmWareUpgrade_FUButton")]'
#XPATH_DASHBOARD_FIRMWARE_SELECT_UPGRADE_BUTTON ='//*[@id="DC_FirmWareUpgrade_FUButton_3"]'
XPATH_DASHBOARD_FIRMWARE_SELECT_UPGRADE_BUTTON ='//*[@id="DC_FirmWareUpgrade_FUButton_1"]'
ID_DASHBOARD_FIRMWARE_UPGRADE_CONFIRM_BUTTON = 'id=DC_Confirm_Window_Ok_Button'
XPATH_DASHBOARD_HEADER_LABEL = '//*[contains(@class, "v-label-dms-featureLabel") and contains(text(), "Dashboard")]'
XPATH_DASHBOARD_REFRESH_PLAY_PAUSE_BUTTON = '//button[@id="DC_Refresh_PlayPauseButton"]'
XPATH_DEVICE_ACTION_POPUP_OK = '//span[contains(translate(text(), "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"),"ok")]'
DEVICE_DASHBOARD_DEVICE_URL = '{dms_device_console}#!mv/dashboard/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
NETWORK_CONSOLE_DASHBOARD_URL = '{dms_device_console}#!dmsui-network-dashboard/?C0'
XPATH_DASHBOARD_DASHBOARD = '//div[contains(@class,v-label-dms-dashboard-menuIcon)]'
XPATH_DASHBOARD_RADIO_POINT_TYPE_LABEL = '//div[@id="RADIO_POINT_TYPE_LABEL"]'
XPATH_DASHBOARD_SOFWARE_VERSION_TEXT= '//div[@id="DC_SoftwareVersion_Value_Label"]'
XPATH_DMS_OUTOFSERVICE_TAG = '//div[contains(@class,"dms-summary-outofservice")]'
XPATH_REPLAN_CONFIRM='//*[@id="DC_Confirm_Window_Ok_Button"]'
XPATH_CONFIRM_CHECKBOX='//*[@id="DC_Confimrm_ChkBox"]'

XPATH_RESTORE='//*[@id="RESTORE"]'
XPATH_LOCAL_RADIO_BUTTON='//*[@id="FileSourceOptionGroup"]/span[2]'
XPATH_APPLY_BUTTON='//*[@id="DC_Restore_Apply_Button"]'
XPATH_CONFIRM_BUTTON='//*[@id="DC_Confirm_Button"]'
XPATH_RESTORE_DELETE='//*[@id="scalar-delete-layout-label"]'
XPATH_RESTORE_OK_BUTTON='//*[@id="DC_DeleteWindow_OK_Button"]'
XPATH_SAVE_BUTTON='//*[@id="DC_Device_Config_Save_Button"]'
XPATH_SERVER_TIME='//*[@id="DC_ServerTime_Layout"]'

## DashboardPage Components
ID_BC_Dashboard_Header = '//*[@id="DC_Dashboard_Header"]'
ID_DC_SummarySerStatus = '//*[@id="DC_SummarySerStatus"]'
ID_DC_Summary_Title = 'id=DC_Summary_Title'
ID_DC_SummaryOUIPC = 'id=DC_SummaryOUIPC'
XPATH_DC_eNodeBNameCA_Title_Label = '//*[@id="DC_eNodeBNameCA_Title_Label"]'
XPATH_DC_ProLedTemp_Title = '//*[@id="DC_ProLedTemp_Title"]'
XPATH_DC_downlinkCaEnableCA_Title_Label = '//*[@id="DC_downlinkCaEnableCA_Title_Label"]'
XPATH_DC_numSectorsPerBCCA_Title_Label = '//*[@id="DC_numSectorsPerBCCA_Title_Label"]'
XPATH_DC_PTP_SourceCA_Title_Label = '//*[@id="DC_PTP.SourceCA_Title_Label"]'
XPATH_DC_Provision_Status_Count_Label = '//*[@id="DC_Provision_Status_Count_VLayoutt"]/div[1]'
XPATH_DC_Provision_Failed_Count_HLayout = '//*[@id="DC_Provision_Status_Count_HLayout"]/div[1]/div'
XPATH_DC_Provision_Delta_Count_HLayout = '//*[@id="DC_Provision_Status_Count_HLayout"]/div[3]/div'
XPATH_DC_Provision_Pending_Count_HLayout = '//*[@id="DC_Provision_Status_Count_HLayout"]/div[5]/div'
XPATH_DC_DashBoard_Sector_Status_Title = '//*[@id="DC_DashBoard_Sector_Status_Title"]'
XPATH_DC_Dashboard_SectorStatus_1 = '//*[@id="DC_Dashboard_SectorStatus"]/div[2]/div[2]/div/div[1]/div'
XPATH_DC_Dashboard_SectorStatus_2 = '//*[@id="DC_Dashboard_SectorStatus"]/div[2]/div[3]/div/div[1]/div'
XPATH_DC_Dashboard_Map = '//*[@id="DC_Dashboard_Map"]'
ID_DC_SoftwareVersionCA_Title_Label = '//*[@id="DC_SoftwareVersionCA_Title_Label"]'
ID_DC_HardwareVersionCA_Title_Label = '//*[@id="DC_HardwareVersionCA_Title_Label"]'
ID_DC_DvcAlarmsCountCA_Title_Label = '//*[@id="DC_DvcAlarmsCountCA_Title_Label"]'
ID_DC_RP_Status_Count_Label = '//*[@id="DC_RP_Status_Count_Lbl"]'
ID_DC_SoftwareVersion_Value_Label = '//*[@id="DC_SoftwareVersion_Value_Label"]'
ID_DC_Dashboard_TimingSrcInUse = '//*[@id="DC_Dashboard_TimingSrcInUse"]'
XPATH_Number_of_Critical_Alarm = '//*[@id="alarmValue"]/div[1]/div'
XPATH_Number_of_Major_Alarm = '//*[@id="alarmValue"]/div[3]/div'
XPATH_Number_of_Minor_Alarm = '//*[@id="alarmValue"]/div[5]/div'
XPATH_Number_of_Warning_Alarm = '//*[@id="alarmValue"]/div[7]/div'
ID_DC_LocalIPAddressTitle_Title_Label = '//*[@id="DC_LocalIPAddressTitle_Label"]'
ID_DC_LocalIPAddressTitle_Value_Label = '//*[@id="DC_LocalIPAddress_Value_Label"]'
ID_DC_accessUtilities_Title_Label = '//*[@id="accessUtilities"]'
ID_DC_accessUtilities_WebGUI_Label = '//span[contains(text(),"WebGUI")]'
ID_DC_accessUtilities_SSH_Label = '//span[contains(text(),"SSH")]'
ID_DC_DashBoard_DeviceDetails_Title = '//*[@id="DC_DashBoard_DeviceDetails_Title"]'
ID_DC_FirstUseDate_Title_Label = '//*[@id="DC_FirstUseDate _Title_Label"]'
ID_DC_LastActivationTime_Title_Label = '//*[@id="DC_LastActivationTime _Title_Label"]'
ID_DC_LastContactTime_Title_Label = '//*[@id="DC_LastContactTime _Title_Label"]'
ID_DC_LocalTimeZoneTitle_Label = '//*[@id="DC_LocalTimeZoneTitle_Label"]'
ID_DC_FactorySerialNumberTitle_Label = '//*[@id="DC_FactorySerialNumberTitle_Label"]'
ID_DC_FactorySerialNumber_Value_Label = '//*[@id="DC_FactorySerialNumber_Value_Label"]'
ID_DC_FriendlyName_Label = '//*[@id="userTag_title"]'
ID_DC_Dashboard_Device_History = '//*[@id="DC_Dashboard_Device_History"]'
ID_DC_Dashboard_Device_pnp_status = '//*[@id="DC_Dashboard_Devicepnpstatus"]'