# XPATH_DEVICE_STATUS_PNP= '//*[@id="DC_Menu_devicepnp_ID"]/*[text()="Device PnP Status"]'
# ID_DMS_LOGIN_USER= 'id=usernameTf'
# ID_DMS_LOGIN_PASSWORD= 'id=passwordTf'
# ID_DMS_LOGIN_SIGNIN= 'id=signinbutton'
# ID_MENU_ACTION= 'id=menu-action'
# CTL_MAIN_SCREEN_DEVICE_INPUT = 'TEST'
# Overwrridden Parameter
# XPATH_OWP_PROFASSO_PROFILE_ASSOCIATION = '//*[text()="Profile Association"]/parent::*/parent::*'
# XPATH_OWP_PROFASSO_LOAD_SERVICE_SETTING_BUTTON='//div[@id="ProfileAssociation.ServiceArea"]//div[@role="button"]'
# XPATH_OWP_PROFASSO_CHOOSE_FILE= '//input[@type="file"]'
# XPATH_OWP_PROFASSO_ADD_NEW_PROFILE='id=addNewBtn'
# ID_OWP_PROFASSO_DC_CONFIG = 'id=DC_Menu_configuration_ID'
# ID_OWP_PROFASSO_PROF_ASSO = 'id=DC_Profile Association'
# ID_OWP_PROFASSO_FILE_UPLOAD_OK_BUTTON = 'id=DC_FileUpload_OkBtn'
# ID_OWP_PROFASSO_CONFIG_SAVE_BUTTON = '//button[@id="DC_Device_Config_Save_Button"]'
# XPATH_OWP_CARRIER_AGGRE_BUTTON= '//div[@id="DC_Carrier Aggregation"]//div[contains(@class,"v-button")]'
# XPATH_OWP_DOWNLINK_CA_VALUE = '//span[contains(text(),"{value}")]'
# XPATH_OWP_FILTER_DROPDOWN_BUTTON= '//div[@class="v-filterselect-button"]'
# ID_OWP_DEVICE_CONFIG_SAVE_BUTTON= 'id=DC_Device_Config_Save_Button'
# ID_OWP_OVERRIDDEN_PARAM_HEADER = 'id=DC_DMS Overridden Params_Header'
# #PNP PAGE
# ID_PNP_MAIN_PAGE= '//*[@id="DC_Menu_devicepnp_ID"]'
# ID_PNP_WOKFLOW = 'id=DC_PnPStatus_PnPWorkflow_Box'
# ID_PNP_MAIN_PAGE_BUTTON='id=DC_Menu_devicepnp_ID'
# XPATH_PNP_WORKFLOW_TAG = '//*[text()="PnP Workflow"]'
# ID_PNP_PAGE_STATUS_HEADER='id=DC_Device PnP Status_Header'
# XPATH_WORKFLOW_STEP_FAILED='//div[contains(@class,"v-verticallayout-stepFailed")]'
# XPATH_CONTAIN_DMS_SUMMARY_INSERVICE='//div[contains(@class,"dms-summary-inservice")]'
# XPATH_CONTAIN_DMS_SUMMARY_OUTOFSERVICE='//div[contains(@class,"dms-summary-outofservice")]'
# XPATH_PNP_WORKFLOW_FINISHED_ON_TEXT = '//b[contains(text(),"finished on")]'
# XPATH_PNP_WORKFLOW_STATUS_STRING='//div[@class="v-label v-widget v-has-width"]'
# Dashboard Page
ID_DASHBOARD_DASHBOARD_BUTTON = 'id=DC_Menu_Content_Dashboard_Button'
XPATH_DMS_INSERVICE_TAG = '//div[contains(@class,"dms-summary-inservice")]'
ID_DASHBOARD_LAST_CONTACT_TIME = 'id=DC_LastContactTime_Value_Label'
XPATH_DASHBOARD_CONNECT_DEVICE = '//div[contains(@class,"v-csslayout-per-device-action-connect")]'
XPATH_DASHBOARD_REBOOT_DEVICE = '//div[contains(@class,"v-csslayout-per-device-action-reboot")]'
XPATH_DASHBOARD_REPLAN_DEVICE = '//div[contains(@class,"v-csslayout-per-device-action-replan")]'
ID_DASHBOARD_HEADER_STRING = 'id=DC_Dashboard_Header'
XPATH_DASHBOARD_REFRESH_PLAY_PAUSE_BUTTON = '//button[@id="DC_Refresh_PlayPauseButton"]'
XPATH_DEVICE_ACTION_POPUP_OK = '//span[text()="Ok"]'
DEVICE_DASHBOARD_DEVICE_URL = '{dms_device_console}#!mv/dashboard/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
# #Notification Popup
# XPATH_NOTIFICATION_STATUS_VERIFICATION_DEVICE = '//div[@id="DC_Notification_PopUp_Container"]/*/div[3]//*[contains(text(),"{verify_string}")]'
# ID_NOTIFICATION_HEADER= 'id=DC_Header_Notifications_Layout'
# ID_NOTIFICATION_POPUP_CONTAINER = 'id=DC_Notification_PopUp_Container'
# #Provisioning Status
# XPATH_PROVISION_MAIN_MENU= '//div[contains(@class,"v-label-dms-provisioning-menuIcon")]'
# XPATH_PROVISION_STATUS_MAIN= '//div[@id="DC_Menu_provisioningStatus_ID"]/div[contains(@class,"sub-menuIcon-menuIcon")]'
# XPATH_PROVISION_TEXT_VERIFY_TEMPLATE = '//div[contains(text(),"{}")]'
# ID_PROVISIONING_STATUS_HEADER= 'id=DC_Provisioning Status_Header'
# #NetworkConsole
#
# #page path
#
# DEVICE_CONSOLE_TIME_URL='{dms_device_console}#!mv/timingsource/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
# DEVICE_PNP_PAGE='{dms_device_console}#!mv/devicepnp/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
# DEVICE_OVERWRRIDDEN_PARAMETER='{dms_device_console}#!mv/configuration/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
# DEVICE_PROVISIONING_STATUS= '{dms_device_console}#!mv/provisioningStatus/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
# DEVICE_ALARMS_PAGE='{dms_device_console}#!mv/devicealarms/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
# DEVICE_HISTORY_PAGE= '{dms_device_console}#!mv/devicehistory/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
# DEVICE_KPI_PAGE= '{dms_device_console}#!mv/devicekpi/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
