
SELECT_VENUE_FILE='//span[contains(text(),"Venue File")]'
FOLDER_BUTTON='//*[@id="DMS_FOLDER_OPEN_DEBUG_ID"]'
UPLOAD_OK_BUTTON='//*[@id="NC_FileImport_Upload"]'
IMPORT_BUTTON='//*[@id="NC_FileImport_ImportButton"]'
OPERTION_HISTORY_BUTTON='//*[@id="NC_DMSHeader_Operation_History_Button"]'
OPERTION_HISTORY_RESOURCE_NAME='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[4]/div/div'
OPERTION_HISTORY_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[5]/div'
OPERTION_HISTORY_OPERATION_STATUS='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[6]/div/div'

XPATH_OH_RESOURCE_NAME='//div[@id="DMS_Operation_History_Table"]//div[2]//div//div//div[4]//input[1]'
XPATH_OH_OPERATION_TYPE='//div[@id="DMS_Operation_History_Table"]//div[2]//div//div//div[5]//input[1]'
ID_OH_APPLY_BUTTON='//*[@id="DC_OperationHistory_ApplyFilter_Button"]'

SHOW_ADVANCE_OPTION='//*[@id="showAdvanceBtn"]'
PRO_ASSOCIATION_INPUT='//*[@id="existingProAssoTable"]/div[2]/div/div/div[2]/input'
APPLY_FILTER='//*[@id="applyFilterBtn"]'
ADD_BUTTON='//*[@id="addButton"]'
SAVE_BUTTON='//*[@id="DC_Device_Config_Save_Button"]'
SELECT_CHECKBOX='//*[@id="existingProAssoTable"]/div[3]/div[1]/table/tbody/tr/td[1]'
XPATH_DELETE_CHECKBOX='//*[@id="headerCheckBox"]'
XPATH_DELETE_BUTTON='//*[@id="deleteBtn"]'
XPATH_ADD_BUTTON='//*[@id="addNewBtn"]'
XPATH_PROFILE_ASSOCIATIOn_BUTTON_CLICK='//*[@id="ProfileAssociation.ServiceArea"]/div[2]/div'
XPATH_CHOOSE_FILE='//*[@id="SS_FileUpload"]'
XPATH_CLICK_OK_BUTTON='//*[@id="DC_FileUpload_OkBtn"]'
XPATH_ORP_PARAM_SAVE_BUTTON = '//*[@id="DC_Device_Config_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP = '//*[contains(text(),"Saved successfully")]'



ENTERPRISE_VIEW_HEADER = '//div[@id="DC_Menu_Content_Get_Menu_Content_Page"]/div[1]/div/div/div'
SEARCH_VENUE = '//*[@id="searchTextField"]'
VENUE_SEARCH_BUTTON = '//*[@id="searchBtn"]'
VENUE_NAME = '//label[@id="eachAddressLbl1"]'
TOTAL_DEVICE_COUNT = '//div[@id="devices_count"]'
actual_device_count = '5'
VENUE_CUCP_VNF_ID = '//span[contains(text(),"ipsec2-2051cucp1")]'
VENUE_CUUP_VNF_ID = '//span[contains(text(),"ipsec2-2051cuup1")]'
VENUE_DU_VNF_ID = '//span[contains(text(),"ipsec2-2051du1")]'
VENUE_DU_RP_VNF_ID = '//div[contains(text(),"ipsec2-2051du1_0005B9514245_1")]'
VENUE_BC_MAC_ID = '//span[contains(text(),"0005B9423AB2")]'
VENUE_BC_RP_MAC_ID = '//div[contains(text(),"0005B9423AB2_0005B9519AA1_1")]'
VENUE_CUCP_SA = '//div[contains(text(),"ipsec2-2051cucp1")]'
VENUE_CUUP_SA = '//div[contains(text(),"ipsec2-2051cuup1")]'
VENUE_DU_SA = '//div[contains(text(),"ipsec2-2051du1")]'
VENUE_BC_SA = '//div[contains(text(),"BC_Automation_1")]'
#CUCP_REPLAN_STATUS = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[3]/div[1]/table/tbody/tr[3]/td[4]/div/div/i'
CUCP_REPLAN_STATUS ='//*[@id="NC_DeviceList_PagedFilterTable"]/div[2]/div[1]/table/tbody/tr[3]/td[4]/div/div/i'
#CUUP_REPLAN_STATUS = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[3]/div[1]/table/tbody/tr[1]/td[4]/div/div/i'
CUUP_REPLAN_STATUS = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[2]/div[1]/table/tbody/tr[1]/td[4]/div/div/i'
#DU_REPLAN_STATUS = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[3]/div[1]/table/tbody/tr[2]/td[4]/div/div/i'
DU_REPLAN_STATUS = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[2]/div[1]/table/tbody/tr[2]/td[4]/div/div/i'
#BC_REPLAN_STATUS = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[3]/div[1]/table/tbody/tr[4]/td[4]/div/div/i'
BC_REPLAN_STATUS = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[2]/div[1]/table/tbody/tr[4]/td[4]/div/div/i'
VIEW_BUILDING_BUTTON = '//button[@id="viewBuildingBtn"]'
VIEW_FLOOR_BUTTON = '//*[@id="floorNavBtn"]'
MANAGE_FLOOR_PLAN = '//*[@id="NC_Upload_FloorPlan_Button"]'
CUCP_COUNT = '//span[contains(text(),"CUCP: 1")]'




DMS_Overridden_params_at_venue='//*[@id="venueCfgOvrBtn"]'
show_DMS_overridden_params='//*[@id="NC_VenueCfgOvr_Content"]/div[1]/span[2]'
#Device_type='//*[@id="NC_VenueCfgOvr_devType_combobox"]/div'
DEVICE_type_input='//*[@id="NC_VenueCfgOvr_devType_combobox"]/input'
Device_Software_Version='//*[@id="NC_VenueCfgOvr_swVer_combobox"]/input'
XAPTH_Device_type_LIST_ELEMENT_DU='//span[contains(text(),"0005B9-CS_ONECELL_DU")]'
XAPTH_Device_type_LIST_ELEMENT_CUCP='//span[contains(text(),"0005B9-CS_ONECELL_CU-CP")]'
XAPTH_Device_type_LIST_ELEMENT_CUUP='//span[contains(text(),"0005B9-CS_ONECELL_CU-UP")]'
XAPTH_Software_Version_LIST_ELEMENT='//span[contains(text(),"6.0.0 and above")]'


Venue_SEARCH_INPUT_TEXT='//*[@id="DC_Search_TextField"]'
VEnue_SEARCH_BUTTON='//*[@id="DC_Search_Button"]/span'
VENUE_COLLAPSE_EXPAND_BUTTON='//*[@id="DC_ExpandCollapse"]'

ID_ORP_SEARCH_INPUT = 'id=DC_Search_TextField'
ID_ORP_SEARCH_BUTTON = 'id=DC_Search_Button'
XPATH_ORP_SECTOR_TAB = '//div[div[div[contains(text(), "{sector}")]]]'
XPATH_ORP_COLLAPSE_EXPAND_BUTTON = '//*[contains(text(), " All")]/parent::button'
XPATH_ORP_COLLAPSE_EXPAND_TEXT = '//*[@id="DC_ExpandCollapse"]/span'
XPATH_ORP_SCALAR_PARAM_INPUT = '//*[contains(text(), "{section}")]//ancestor::div[1]//following-sibling::div//*[contains(text(), "{overridden_param}")]/parent::div//input'
XPATH_ORP_TABULAR_PARAM_INPUT = '//*[contains(text(), "{section}")]//ancestor::div[1]//following-sibling::div//input[contains(@id, "{overridden_param}")]'
XPATH_ORP_PARAM_SAVE_BUTTON = '//*[@id="DC_Device_Config_Save_Button"]'

XAPTH_VES_PROVISIONED_DATA='//*[@id="DC_VES Collector Configuration"]'

#CLICK_ON_VIEW_BUILDING = '//*[@id="viewBuildingBtn"]'
CLICK_ON_VIEW_BUILDING ='//button[@id="viewBuildingBtn"]'
GET_BUILING_DETAILS = '//*[@id="buildingForm"]'
CLICK_ON_VIEW_FLOOR = '//*[@id="floorNavBtn"]'
CLICK_ON_MANAGE_ELEMENT_FLOOR1 = '//*[@id="NC_Upload_FloorPlan_Button"]'
#GET_CU_CP_SUMMARY_DETAILS = '// span[contains(text(), "CUCP: 1")]'
GET_CU_CP_SUMMARY_DETAILS = '//span[contains(text(),"CUCP: 1")]'
GET_CU_UP_SUMMARY_DETAILS = '//span[contains(text(),"CUUP: 1")]'
GET_DU_SUMMARY_DETAILS = '//span[contains(text(),"DU: 1")]'

XPATH_VES_URL_CUCP='//*[@id="DC_cucp_vesUrl_TF"]'
XPATH_VES_USERNAME_CUCP='//*[@id="DC_cucp_vesUserName_TF"]'
XPATH_VES_PASSWORD_CUCP='//*[@id="DC_cucp_vesPassWord_TF"]'
XPATH_VES_URL_CUUP='//*[@id="DC_cuup_vesUrl_TF"]'
XPATH_VES_USERNAME_CUUP='//*[@id="DC_cuup_vesUserName_TF"]'
XPATH_VES_PASSWORD_CUUP='//*[@id="DC_cuup_vesPassWord_TF"]'
CLICK_EXPORT_BUTTON = '// *[ @ id = "viewExportBtnOnInfo"]'
XPATH_VENUE_EXPORT_STATUS = '//div[contains(text(),"Success")]'

XPATH_LOCATION_DROPDOWN = '//*[@id="dropdowntoggle"]'
XPATH_SEARCH_LOCATION = '//div[@id="searchLocOpt"]'
XPATH_LOCATION_FIELD = '//input[@id="searchTextField"]'
XPATH_SEARCH_BUTTON = '//*[@id="searchBtn"]'
XPATH_ADDRESS_1 = '//*[@id="eachAddressLbl1"]'
XPATH_CREATE_VENUE_BTN = '//*[@id="drawBoundaryBtn"]'
XPATH_DRAW_RECTANGLE = '//*[@id="rectToolBtn"]'

XPATH_VIEW_BUILDING = '//button[@id="viewBuildingBtn"]'
XPATH_VIEW_FLOOR = '//button[@id="floorNavBtn"]'
XPATH_MANAGE_FLOOR = '//div[@id="NC_Upload_FloorPlan_Button"]'
XPATH_ADD_DEVICE_TO_FLOOR = '//span[contains(text(),"Add Device")]'
#XPATH_SUCCESS_MESSAGE_ADD = '//*[@id="networkconsole-1878154089-overlays"]/div'
XPATH_SUCCESS_MESSAGE_ADD = '//*[@id="networkconsole-1878154089-overlays"]/div[2]/div/div/p'
XPATH_NC_FLOOR_SAVE = '//button[@id="NC_Floor_Plan_Save_Button"]'
XPATH_SAVE_CLOSE = '//span[contains(text(),"Save and Close")]'
XPATH_Topology_ADD_SUCCESS = '//*[@id="networkconsole-1878154089"]/div/div[2]/div[4]/div/div/div/div/div[2]'
XPATH_VENUE_CANVAS = '//*[@id="canvas"]'
XPATH_LOCK_DELETE = '//*[@id="NC_Floor_Plan_Del_Device_Button"]/span'
XPATH_SELECT_DELETE = '//*[@id="NC_Floor_Plan_Del_Device_Button"]/span'
XPATH_PC_DROPDOWN ='//*[@id="DC_DeviceType_Combobox"]/div'
XPATH_PC_UP = '//span[contains(text(),"0005B9-CS_ONECELL_CU-UP")]'
XPATH_PC_DU = '//span[contains(text(),"0005B9-CS_ONECELL_DU")]'
XPATH_PC_BC = '//span[contains(text(),"0005B9-LTE_Enterprise_C-RANSC_Cntrl")]'
XPATH_VES_param_1='(//*[@id="scalar-delete-layout-label"])[1]'
XPATH_VES_param_2='(//*[@id="scalar-delete-layout-label"])[2]'
XPATH_VES_param_3='(//*[@id="scalar-delete-layout-label"])[3]'
XPATH_ORP_PARAM_SAVE_BUTTON_gNB = '//*[@id="DC_Device_Config_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP_gNB = '//*[contains(text(),"Saved successfully")]'
XAPTH_Device_type_LIST_ELEMENT_BC='//span[contains(text(),"0005B9-LTE_Enterprise_C-RANSC_Cntrl")]'



XPATH_TOGGLE_BUTTON='//*[@id="rptoggleButton"]'

CLICK_GENERATE_GSC_BUTTON = '//button[@id="viewGenerateBtn"]'
CLICK_GENERATE_BUTTON = '//span[contains(text(),"Generate")]'
XPATH_GNBID_SELECTOR = '//*[contains(text(), "{input}")]/parent::div/following::div//input'
XPATH_VENUE_EXPORT_MSG = '//body[1]/div[1]/div[1]/div[2]/div[4]/div[1]/div[1]'
XPATH_MAP_DETAIL = '//b[contains(text(),"csblrlabsvtcc1ec16-1016cucp1")]'
XPATH_View = 'id = dashboard_map_neighbor_popup-content'
XPATH_topo_value='//*[@id="dashboard_map_neighbor_popup"]'
XPATH_CUUP_COUNT='//*[@id="cuUserPlane"]/div/div[2]/div/div[1]/div/a'
XPATH_CU_DETAIL ='//*[@id="cuUserPlane"]/div'
XPATH_DU_DETAIL ='//*[@id="distributedUnit"]/div'
XPATH_RU_DETAIL = '//*[@id="DC_CUCP_UP_Rp_Status_Count_VLayoutt"]'
XPATH_CP_DETAIL = '//*[@id="cuControlPlane"]/div'
XPATH_DU_RU_DETAIL = '//*[@id="DC_DU_Rp_Status_Count_VLayoutt"]'