XPATH_ALARM_MENU = "//*[@id='DC_Menu_devicealarms_ID']/div[1]"
ID_DASHBOARD_ALARM_HEADER ='id=DC_Alarms_Header'
ID_GNB_ALARM_PAGE_HEADER = 'DC_Alarms_Header'
XPATH_EVENTTYPE_SEARCH_INPUT = '//*[@id="DC_ACTIVE_DEVICE_ALARM_Events_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[4]/div/input'
ID_ALARM_APPLY_BUTTON = 'id=applyFilter'
XPATH_ALARM_SEVERITY = '//*[@id="DC_ACTIVE_DEVICE_ALARM_Events_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[3]/div/div'
XPATH_ALARM_PROBABLE_CAUSE = '//*[@id="DC_ACTIVE_DEVICE_ALARM_Events_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[6]/div'
XPATH_ALARM_SPECIFIC_PROBLEM = '//*[@id="DC_ACTIVE_DEVICE_ALARM_Events_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[7]/div'
XPATH_NW_ALARM_SEVERITY = '//*[@id="DC_DeviceAlarms_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[3]/div/div'
XPATH_NW_ALARM_PROBABLE_CAUSE = '//*[@id="DC_DeviceAlarms_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[6]/div'
XPATH_NW_ALARM_SPECIFIC_PROBLEM = '//*[@id="DC_DeviceAlarms_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[7]/div'
XPATH_NWEVENTTYPE_SEARCH_INPUT = '//*[@id="DC_DeviceAlarms_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[4]/div/input'
ID_NWALARM_APPLY_BUTTON = 'id=DeviceAlarms_AppyFilterButton'
#XPATH_NW_ALARM_SEVERITY = '//*[@id="DC_DeviceAlarms_FilterTable"]/div[2]/div[1]/table/tbody/tr[1]/td[3]/div/div'
#XPATH_NW_ALARM_PROBABLE_CAUSE = '//div[contains(text(),"F1Connectionisdown")]'
XPATH_ALL_ALARM ='//div[contains(text(),"All")]'
XPATH_ALL_EVENTTYPE_SEARCH_INPUT ='//*[@id="DC_ALL_DEVCIE_ALARM_Events_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[4]/div/input'
XPATH_CLEAR_ALARM_SEVERITY = '//div[contains(text(),"CLEAR")]'

XPATH_ALARM_SETTINGS = '//*[@id="DC_ACTIVE_DEVICE_ALARM_Events_FilterTable"]/div[1]/div[2]'
XPATH_ADDITIONAL_INFO = '//div[contains(text(),"Additional Info")]'
XPATH_ALARM_TABLE = '//*[@id="DC_ACTIVE_DEVICE_ALARM_Events_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[9]/div'
#XPATH_ALARM_TABLE = '//*[@id="DC_ACTIVE_DEVICE_ALARM_Events_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[10]/div'
CUCP_gNBid = '1004'
CUCP_Alarm_VNFID = 'ipsec2-2051cucp1'
CUCP_gNBName = 'VenueAutomation'
CUUP_gNBid = '1005'
CUUP_Alarm_VNFID = 'ipsec-11001cuup1'
CUUP_gNBName = 'VenueAutomation'
DU_gNBid = '2051'
DU_Alarm_VNFID = 'ipsec2-2051du1'
DU_gNBName = 'VenueAutomation'

ID_SYNC_ALARM = 'id=SyncAlarmButton'
XPATH_SYNC_ALARM_SEVERITY='//*[@id="DC_ACTIVE_DEVICE_ALARM_Events_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[3]/div/div'
XPATH_SYNC_CLEAR_ALARM_SEVERITY = '//*[@id="DC_ALL_DEVCIE_ALARM_Events_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[3]/div/div'
XPATH_SYNC_ALARM_ROW = '//div[contains(text(),"Sync Alarms Response")]'
XPATH_RESPONSE_SEVERITY = '//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[7]/td[3]/div/div'
XPATH_DU_RESPONSE_SEVERITY = '//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[7]/td[4]/div/div'

XPATH_PNP_MINMANDATORY = '//*[@id="DC_PnPStatus_Box_Provision Min Mandatory Conf"]/div[2]/div'
XPATH_FAILURE = '//*[@id="DC_Grid_Table_Label_Text_Failure Reason"]'
XPATH_ENABLE_PAGE = '//*[@id="DC_CONTENT_LAYOUT_FeatureHeadingLayout"]/div[2]/div'
Failure_Reason = 'Computation failed. Could not find value for PnP mandatory attribute:PLMN.mcc, of service(s): GNBCONF, Please check logs for more details'
Failure_Reason_UP = 'Computation failed. Could not find value for PnP mandatory attribute:CUUP_gNBId, of service(s): GNBCONF, Please check logs for more details'
Failure_Reason_DU = 'Computation failed. Could not find value for PnP mandatory attribute:gNBId, of service(s): GNBCONF, Please check logs for more details'
Severity = 'MAJOR'
Event_Type = 'VNF Provisioning Failure'
Probable_cause = 'Minimum configuration unavailable'
Specific_Problem = 'Minimum mandatory configuration is not available for the gNB-VNF. gNB-VNF=alarmtest-8001cucp1;'
XPATH_GEAR_ICON = '//*[@id="NC_DeviceAlarms_FilterTable"]/div[1]/div[2]'
XPATH_ADDITIONAL_TEXT = '//div[contains(text(),"Additional Text")]'
ADDITIONAL_TEXT = 'Parameter(s) PLMN.mcc not available during computation'
XPATH_SYSTEM_ALARM_TABLE = '//*[@id="NC_DeviceAlarms_FilterTable"]/div[2]'
#XPATH_SYSTEM_ALARM_TABLE = '//*[@id="NC_SystemAlarmstabsheet"]'
XPATH_INPUT_PROBABLE = '//tbody/tr[2]/td[6]/div[1]/input[1]'
XPATH_APPLY_FILTER = '//*[@id="DeviceAlarms_AppyFilterButton"]/span'
XPATH_SPECIFIC_PROBLEM = '//tbody/tr[2]/td[7]/div[1]/input[1]'
cucp = '8001cucp1'
cuup = '8001cuup1'
du = '8001du1'
Source = 'DMS_NP'
Acknowledgement = 'Un-Acknowledged'
XPATH_DETAILS = '//tbody/tr[1]/td[9]/div[1]/div[1]/div[1]/div[1]/span[1]'
XPATH_EVENT_TYPE = '//body/div[@id="networkconsole-1878154089-overlays"]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]'
XPATH_SOURCE = '//*[@id="networkconsole-1878154089-overlays"]/div[3]/div/div/div[3]/div/div/div[1]/div/div[2]/div'
XPATH_PROBABLE_CAUSE = '//body/div[@id="networkconsole-1878154089-overlays"]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]'
XPATH_SCROLL = '//*[@id="NC_DeviceAlarms_FilterTable"]/div[2]'
XPATH_OCCURENCE = '//*[@id="networkconsole-1878154089-overlays"]/div[3]/div/div/div[3]/div/div/div[3]/div/div[2]/div[1]/table/tbody/tr[1]/td[2]/div/div'
OCCURENCE = 'Alarm Re-occurred'
OCCURENCE_REASON = 'Additional Text of the alarm is changed'


XPATH_GET_ALARM_DETAILS = '//div[contains(text(),"No alarms found")]'
XPATH_NW_GET_ALARM_DETAILS = '//*[@id="DC_DeviceAlarms_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[3]'
XPATH_NW_SPECIFIC_PROBLEM_SEARCH_INPUT = '//*[@id="DC_DeviceAlarms_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[7]/div/input'
XPATH_ALL_SPECIFIC_PROBLEM_SEARCH_INPUT ='//*[@id="DC_ALL_DEVCIE_ALARM_Events_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[7]/div/input'
ID_NOTIFICATION_BUTTON = 'id=DC_Header_Notifications_Layout'
ID_ALL_NOTIFICATION_BUTTON = 'DC_SeeAll_Notification_Link'
ID_NOTIFICATION_SEARCH_BUTTON = 'id=DC_NotifyAllWindow_SearchButton'
ID_NOTIFICATION_SEARCH = 'id=DC_NotifyAllWindow_SearchField'
XPATH_SYNC_NOTIFICATION = "//*[@id='DC_NotifyAllWindow_Disclosure_0']/div[3]/div[1]/div"
XPATH_ACTION_NOTIFICATION = "//*[@id='DC_NotifyAllWindow_Disclosure_1']/div[3]/div[1]/div"