DEVICE_HISTORY_PAGE = '{dms_device_console}#!mv/devicehistory/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
ID_DEVICE_HISTORY_PAGE_HEADER = 'id=DC_Device History_Header'
XPATH_DEVICEHISTORY_TBAULAR_TAB = '//*[text()="{tab_type}"]'
XPATH_DEVICEHISTORY_TIMEOPTION_LIST_DISPLAYER = '//*[@id="selectTimeOption"]/div'
XPATH_DEVICEHISTORY_TIMEOPTION_LISTITEM = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]//span[contains(text(),"{time_option}")]/parent::td'
XPATH_DEVICEHISTORY_TIMEOPTION_CHECKBOX = '//*[@id="DC_Tree_Container"]//span[contains(text(), "{event_type}")]'
ID_DEVICEHISTORY_SHOW_BUTTON = 'id=showButton'
ID_DEVICEHISTORY_EXPORT_BUTTON = 'id=DC_DeviceHistory_Export_Button'
BreadCrumb='//*[@id="BreadCrumbLayout"]/div[4]'
XPATH_RESULT_PANEL_INPUT='//*[@id="resultPanel"]/div[3]/div/div/div[3]/div/div[1]/div/div[3]/div/input'
XPATH_RESULT_PANEL_BUTTON='//*[@id="resultPanel"]//div[@class="v-filterselect-button"]'
XPATH_TREE_NODE='//div[@class="v-tree-node-caption-unchecked"]//span[contains(text(),"COMPUTATION")]'
XPATH_OWP_DOWNLINK_CA_VALUE_TO_GET = '//input[@class="v-filterselect-input"]'
XPATH_OWP_DOWNLINK_CA_VALUE = '//span[contains(text(),"{value}")]'
XPATH_BLACKLIST_ROW='//div[@class="v-table-cell-wrapper"][contains(text(),"Blacklist Computation")]'
XPATH_RESULT_PANEL='//div[contains(@class,"Devicehistory")]'
#XPATH_NEW_VALUE='//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[1]/td[4]'
XPATH_POLICY_RESPONSE="//div[text()='Policy Response']"
XPATH_RESPONSE_NAME="//div[text()='Policy Name']/../following-sibling::td/div/div[text()='{}']"
XPATH_RESPONSE_SUCCESS="//div[text()='Success']"
XPATH_CLOSE_BUTTON="//div[@aria-label='close button']"
XPATH_NEW_VALUE='//*[@id="DC_DHDetails_Window_Content"]'
XPATH_SPID_ROW='//div[contains(text(),"SPID Computation")]'
XPATH_COMP_NEW_VALUE='//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[2]/td[4]'
XPATH_MIMO_ROW='//div[contains(text(),"MIMO Computation")]'
XPATH_whitelist_ROW_DH='//div[@class="v-table-cell-wrapper"][contains(text(),"Whitelist Computation")]'
XPATH_NGPS_ROW='//div[@class="v-table-cell-wrapper"][contains(text(),"Nominal GPS Value Change")]'
ID_GNB_HISTORY_PAGE_HEADER = 'id=DC_History_Header'

XPATH_RP_NOTIFCATION='//div[contains(text(),"RP Add Notification")]'
XPATH_NOTIFICATION_RP_DETAIL='//div[contains(text(),"CommScope_RP5100")]'
XPATH_GET_PARAMETER_VALUE='//*[@id="resultPanel"]/div[3]/div/div/div[1]/div/div[2]/div[1]/table/tbody/tr[1]/td[3]'
#XPATH_MPLANE_VALUE='//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[91]/td[4]'
XPATH_MPLANE_VALUE='//*[@id="DC_DHDetails_Window"]'

XPATH_whitelist_ROW='//div[@class="v-table-cell-wrapper"][text()="Netconf Provisioning"]'
XPATH_DELETE_VALUE_ROW='//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[4]/td[4]'
XPATH_Resync_Resync_all_ROW='//div[@class="v-table-cell-wrapper"][text()="Resync or Resync All"]'
XPATH_Resync_get_response_ROW='//div[@class="v-table-cell-wrapper"][text()="Netconf Get Response"]'
XPATH_Resync_get_ROW='//div[@class="v-table-cell-wrapper"][text()="Netconf Get"]'
XPATH_Resync_notification_ROW='//div[@class="v-table-cell-wrapper"][text()="RP Sync Notification"]'
XPATH_Resync_add_notification_ROW='//div[@class="v-table-cell-wrapper"][text()="RP Add Notification"]'

XPATH_RP_REBOOT_RESPONSE_NOTIFCATION ='//div[contains(text(),"Device RP Reboot Response")]'
XPATH_NOTIFICATION_RP_REBOOT_DETAIL = '//div[contains(text(),"Success")]'
XPATH_DEVICE_RPREBOOT='//div[@class="v-table-cell-wrapper"][text()="Device RP Reboot"]'
XPATH_DEVICE_RPREBOOT_RESPONSE='//div[@class="v-table-cell-wrapper"][text()="Device RP Reboot Response"]'
XPATH_DEVICE_EVENT_DETAILS='//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]'
XPATH_DEVICE_RPRESET='//div[@class="v-table-cell-wrapper"][text()="Device RP Reset"]'
XPATH_DEVICE_RPRESET_RESPONSE='//div[@class="v-table-cell-wrapper"][text()="Device RP Reset Response"]'
XPATH_DEVICE_NETCONF_GET_RESPONSE='//div[@class="v-table-cell-wrapper"][text()="Netconf Get Response"]'
XPATH_DEVICE_RPADD_NOTIFICATION1='(//div[@class="v-table-cell-wrapper"][text()="RP Add Notification"])[1]'
XPATH_DEVICE_RPADD_NOTIFICATION2='(//div[@class="v-table-cell-wrapper"][text()="RP Add Notification"])[2]'
XPATH_DEVICE_RP52STATE_NOTIFICATION1='(//div[@class="v-table-cell-wrapper"][text()="RP State Notification"])[1]'
XPATH_DEVICE_RP52SYNC_NOTIFICATION1='(//div[@class="v-table-cell-wrapper"][text()="RP Sync Notification"])[1]'
XPATH_DEVICE_RP52STATE_NOTIFICATION2='(//div[@class="v-table-cell-wrapper"][text()="RP State Notification"])[2]'
XPATH_DEVICE_RP52SYNC_NOTIFICATION2='(//div[@class="v-table-cell-wrapper"][text()="RP Sync Notification"])[2]'
XPATH_Reboot_Provisioning_ROW='//div[@class="v-table-cell-wrapper"][text()="Reboot Provision"]'
XPATH_Delta_Provisioning_ROW='//div[@class="v-table-cell-wrapper"][text()="Delta Provision"]'
XPATH_COMPLETE_HISTORY_TABLE='//*[@id="resultPanel"]'
XPATH_Software_Upgarde_Value_Change_Row='//div[@class="v-table-cell-wrapper"][text()="RP Value Change"]'