# Timing source Page
XPATH_TIMING_SOURCE_HEADER_LABEL='//*[@id="DC_Timing Source_Header"]'
XPATH_LATITUDESIGN='//*[@id="DC_NominalGPS.LatitudeSign_ComboBox"]/input'
XPATH_LATITUDESIGN_COMBOBOX='//*[@id="DC_NominalGPS.LatitudeSign_ComboBox"]/div'
XAPTH_DEGREEOFLATITUDE='//*[@id="DC_NominalGPS.DegreesOfLatitude_TF"]'
XPATH_DEGREEOFLONGITUDE='//*[@id="DC_NominalGPS.DegreesOfLongitude_TF"]'
XPATH_DIRECTIONOFALTITUDE='//*[@id="DC_NominalGPS.DirectionOfAltitude_ComboBox"]'
XPATH_ALTITUDE='//*[@id="DC_NominalGPS.Altitude_TF"]'
XPATH_UNCERTAINTY_SEMI_MAJOR='//*[@id="DC_NominalGPS.UncertaintySemiMajor_TF"]'
XPATH_UNCERTAINTY_SEMI_MINOR='//*[@id="DC_NominalGPS.UncertaintySemiMinor_TF"]'
XPATH_UNCERTAINTY_ALTITUDE='//*[@id="DC_NominalGPS.UncertaintyAltitude_TF"]'
XPATH_ORIENTATION_MAJOR_AXIS='//*[@id="DC_NominalGPS.OrientationMajorAxis_TF"]'
XPATH_CONFIDENCE='//*[@id="DC_NominalGPS.Confidence_TF"]'

XPATH_Timing_DROPDOWN_LIST_NEXT_BUTTON = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]//span[contains(text(), "Save")]/parent::div'
#XPATH_ORP_SCALAR_PARAM_INPUT = '//*[contains(text(), "{section}")]//ancestor::div[1]//following-sibling::div//*[contains(text(), "{overridden_param}")]/parent::div//input'
XPATH_ORP_SCALAR_PARAM_INPUT = '//*[contains(text(),"GPS Configuration")]'
#XPATH_ORP_SCALAR_PARAM_INPUT = '//*[text(),"Nominal"]'
XPATH_TIMING_PARAM_SAVE_BUTTON = '//*[@id="DC_Timing_Source_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP = '//*[contains(text(),"Saved successfully")]'

GPS_TABLE='//*[@id="DC_Nominal GPS Configuration"]'
NTP_SERVER_BOX='//*[@id="DC_PTP.Source_ComboBox"]'
NTP_SERVER='//*[@id="DC_PTP.Source_ComboBox"]/input'
NTP_SERVER_COMBO='//*[@id="DC_PTP.Source_ComboBox"]/div'
NTP_TABLE='//*[@id="DC_Timing Source Configuration"]'
XPATH_WEBGUI_OVERRIDDEN_TABLE='//*[@id="DC_WebGUI-Overridden_Table"]'