EVICE_FILE_IMPORT='//*[@id="NC_FileImport_FileName"]/div'
DEVICE_FILE_TYPE_BUTTON='//*[@id="NC_FileImport_FileTypes"]/div'
SELECT_SERVICE_SETTING_FILE='//span[contains(text(),"Service Settings")]'
SELECT_NETCONF_MOUNT_FILE='//span[contains(text(),"Netconf Mount File")]'
FOLDER_BUTTON='//*[@id="DMS_FOLDER_OPEN_DEBUG_ID"]'
UPLOAD_OK_BUTTON='//*[@id="NC_FileImport_Upload"]'
IMPORT_BUTTON='//*[@id="NC_FileImport_ImportButton"]'
OPERTION_HISTORY_BUTTON='//*[@id="NC_DMSHeader_Operation_History_Button"]'
OPERTION_HISTORY_RESOURCE_NAME='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[4]/div'
OPERTION_HISTORY_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[5]/div'
OPERTION_HISTORY_OPERATION_STATUS='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[6]/div'

SHOW_ADVANCE_OPTION='//*[@id="showAdvanceBtn"]'
PRO_ASSOCIATION_INPUT='//*[@id="existingProAssoTable"]/div[2]/div/div/div[2]/input'
APPLY_FILTER='//*[@id="applyFilterBtn"]'
ADD_BUTTON='//*[@id="addButton"]'
SAVE_BUTTON='//*[@id="DC_Device_Config_Save_Button"]'
SELECT_CHECKBOX='//*[@id="existingProAssoTable"]/div[3]/div[1]/table/tbody/tr/td[1]'
XPATH_DELETE_CHECKBOX='//*[@id="headerCheckBox"]'
XPATH_DELETE_BUTTON='//*[@id="deleteBtn"]'
XPATH_ADD_BUTTON='//*[@id="addNewBtn"]'
XPATH_PROFILE_ASSOCIATIOn_BUTTON_CLICK='//*[@id="ProfileAssociation.ServiceArea"]/div[2]/div'
XPATH_CHOOSE_FILE='//*[@id="SS_FileUpload"]'
XPATH_CLICK_OK_BUTTON='//*[@id="DC_FileUpload_OkBtn"]'
XPATH_ORP_PARAM_SAVE_BUTTON = '//*[@id="DC_Device_Config_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP = '//*[contains(text(),"Saved successfully")]'


SELECT_FACTORY_FILE='//span[contains(text(),"Factory File")]'


Service_Package_Label='//*[contains(text(), "Service Package")]'
Service_Package_DU_Edit_Button="//div[text()='ONECELL5GDU Service Package']/../../td[10]/div/div/div[2]"
Service_Package_CU_Edit_Button="//div[text()='ONECELL5GCU Service Package']/../../td[10]/div/div/div[2]"
ID_ServicePackage_SEARCH_INPUT = '//*[@id="NC_SysProperty_SearchField"]'
ID_ServicePackage_SEARCH_BUTTON = '//*[@id="NC_SysProperty_SearchButton"]'
Raise_alarm_combo='//tbody/tr[3]/td[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]'
XPATH_INPUT_COMBO='//input[@class="v-filterselect-input"]'
COMBO_LIST='//tbody/tr[3]/td[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]'
COMBOX_VALUE_TRUE='//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[2]/td'
SERVICE_PACKAGE_SAVE_BUTTON='//*[@id="NC_ServicePackage_SaveButton"]'
VIEW_PROFILE_BUTTON='//span[contains(text(),"View Profile")]'
NETWORK_CONSOLE_SYSTEM_ALARM_PAGE=''
COMBOX_VALUE_FALSE='//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[1]/td'
#Get_time_filter_table_button='//*[@id="NC_DeviceAlarms_FilterTable"]/div[2]/div/div/div[2]/div/div/span/div'
#XPATH_SPECIFIC_PROBLEM='//*[@id="NC_DeviceAlarms_FilterTable"]/div[2]/div/div/div[7]/input'
XPATH_SPECIFIC_PROBLEM='//*[@id="NC_DeviceAlarms_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[7]/div/input'
XPATH_APPLY_FILTER='//*[@id="DeviceAlarms_AppyFilterButton"]'
XPATH_HEADER_CHECKBOX='//*[@id="headerCheckBox"]'
XPATH_DELETE_BUTTON='//*[@id="NC_ALARM_ONLY_ACTIVE_SYSTEM_ALARM_ACTION_DELETE"]'
XPATH_DELETE_CONFIRM='//*[@id="NC_SYSTEM_ALARM_ACTION_DELETE_Submit_Button"]'
#XPATH_GET_DATA_ROW1='//*[@id="NC_DeviceAlarms_FilterTable"]/div[3]/div[1]/table/tbody/tr/td[3]/div/div'
XPATH_GET_DATA_ROW1='//*[@id="NC_DeviceAlarms_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[3]/div/div'
XPATH_HEART_BEAT_LABEL='//*[@id="DC_HeartBeatStatus_Value_Label"]'
XPATH_CONGFIRM_BUTTON='//*[@id="DC_Confirm_Window_Confirm_Button"]'
XPATH_LICENSE='/html/body/div[3]'
XPATH_CUUP_COMBO='//tbody/tr[3]/td[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]'
#XPATH_TEXT='//*[@id="NC_DeviceAlarms_FilterTable"]/div[3]/div[1]/table/tbody/tr[1]/td[4]/div'
XPATH_TEXT='//*[@id="NC_DeviceAlarms_FilterTable"]/div[2]/div[1]/table/tbody/tr[1]/td[4]'
#XPATH_Event_Type='//*[@id="NC_DeviceAlarms_FilterTable"]/div[2]/div/div/div[4]/input'
#XPATH_Event_Type='//*[@id="NC_DeviceAlarms_FilterTable"]/div[2]/div[1]/table/tbody/tr/td[4]'
XPATH_Event_Type='//*[@id="NC_DeviceAlarms_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[4]/div/input'

XPATH_NETCONF_TEXT='//*[@id="DC_NetCnfSessionStatus_Value_Label"]'

