# Dashboard Page
ID_DASHBOARD_DASHBOARD_HEADER ='id=DC_Dashboard_Header'
XPATH_DASHBOARD_DASHBOARD_SUMMARY = "//div[@id='DC_NetCnfSessionStatusCA_Title_Label']"
ID_DASHBOARD_DASHBOARD_BUTTON = 'id=DC_Menu_Content_Dashboard_Button'
#XPATH_DMS_INSERVICE_TAG = '//div[contains(@class,"dms-summary-inservice")]'
XPATH_DMS_INSERVICE_TAG = '//div[contains(@class,"dms-summary-inservice-sector")]'
ID_DASHBOARD_LAST_CONTACT_TIME = 'id=DC_LastContactTime_Value_Label'
ID_DASHBOARD_LAST_SES_DISCONNECT_TIME ='//*[@id="DC_LastSessDisconnectTime_Value_Label"]'
# XPATH_DASHBOARD_CONNECT_DEVICE = '//div[contains(@class,"v-csslayout-per-device-action-connect")]'
#XPATH_DASHBOARD_CONNECT_DEVICE = '//div[@id="InitiateConnect"]'
XPATH_GNB_DASHBOARD_CONNECT_DEVICE = '//*[@id="InitiateConnect"]/div/div'
# XPATH_DASHBOARD_REBOOT_DEVICE = '//div[contains(@class,"v-csslayout-per-device-action-reboot")]'
XPATH_DASHBOARD_REBOOT_DEVICE = '//div[@id="REBOOT"]'
# XPATH_DASHBOARD_REPLAN_DEVICE  = '//div[contains(@class,"v-csslayout-per-device-action-replan")]'
XPATH_DASHBOARD_REPLAN_DEVICE = '//div[@id="REPLAN"]'
ID_DASHBOARD_RESET_DEVICE = 'id=RESET'
ID_DASHBOARD_RESYNC_DEVICE = 'id=RESYNC'
ID_DASHBOARD_RESYNCALL_DEVICE = 'id=RESYNC_ALL'
ID_DASHBOARD_FIRMWARE_UPGRADE_BUTTON = 'id=FIRMWARE'
#XPATH_DASHBOARD_FIRMWARE_SELECT_UPGRADE_BUTTON = '//*[contains(text(), "5_5_firmware")]/parent::td/following-sibling::td[2]//div[contains(@id, "DC_FirmWareUpgrade_FUButton")]'
XPATH_DASHBOARD_FIRMWARE_SELECT_UPGRADE_BUTTON ='//*[@id="DC_FirmWareUpgrade_FUButton_3"]'
ID_DASHBOARD_FIRMWARE_UPGRADE_CONFIRM_BUTTON = 'id=DC_Confirm_Window_Ok_Button'
XPATH_DASHBOARD_HEADER_LABEL = '//*[contains(@class, "v-label-dms-featureLabel") and contains(text(), "Dashboard")]'
XPATH_DASHBOARD_REFRESH_PLAY_PAUSE_BUTTON = '//button[@id="DC_Refresh_PlayPauseButton"]'
XPATH_DEVICE_ACTION_POPUP_OK = '//span[contains(translate(text(), "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"),"ok")]'
DEVICE_DASHBOARD_DEVICE_URL = '{dms_device_console}#!mv/dashboard/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
NETWORK_CONSOLE_DASHBOARD_URL = '{dms_device_console}#!dmsui-network-dashboard/?C0'
XPATH_DASHBOARD_DASHBOARD = '//div[contains(@class,v-label-dms-dashboard-menuIcon)]'
XPATH_DASHBOARD_RADIO_POINT_TYPE_LABEL = '//div[@id="RADIO_POINT_TYPE_LABEL"]'
XPATH_DASHBOARD_SOFWARE_VERSION_TEXT= '//div[@id="DC_SoftwareVersion_Value_Label"]'
XPATH_DMS_OUTOFSERVICE_TAG = '//div[contains(@class,"dms-summary-outofservice")]'
XPATH_REPLAN_CONFIRM='//*[@id="DC_Confirm_Window_Ok_Button"]'
XPATH_CONFIRM_CHECKBOX='//*[@id="DC_Confimrm_ChkBox"]'

XPATH_RESTORE='//*[@id="RESTORE"]'
XPATH_LOCAL_RADIO_BUTTON='//*[@id="FileSourceOptionGroup"]/span[2]'
XPATH_APPLY_BUTTON='//*[@id="DC_Restore_Apply_Button"]'
XPATH_CONFIRM_BUTTON='//*[@id="DC_Confirm_Button"]'
XPATH_RESTORE_DELETE='//*[@id="scalar-delete-layout-label"]'
XPATH_RESTORE_OK_BUTTON='//*[@id="DC_DeleteWindow_OK_Button"]'
XPATH_SAVE_BUTTON='//*[@id="DC_Device_Config_Save_Button"]'
XPATH_MANAGED_BUTTON='//*[@id="ManageOrUnManage"]'
XPATH_INPUT_UNMANAGED_MANAGED='//*[@id="DC_ManageOrUnmanage_Window_Content"]/div[3]/div/div[2]/textarea'
XPATH_MANAGED_CONFIRM_BUTTON='//*[@id="DC_Confirm_Window_Confirm_Button"]'
XPATH_NETCONF_CONNECTION_STATUS='//*[@id="DC_NetCnfSessionStatus_Value_Label"]'

# DashboardPage
ID_DC_Dashboard_Header = '//*[@id="DC_Dashboard_Header"]'
ID_DC_SummarySerStatus = 'id=DC_SummarySerStatus'
ID_DC_Summary_Title = 'id=DC_Summary_Title'
ID_DC_SummaryOUIPC = 'id=DC_SummaryOUIPC'
ID_DC_MaintenanceStatus = 'id=DC_MaintenanceStatus'
XPATH_DC_gNBIdCA_Title_Label = '//*[@id="DC_gNBIdCA_Title_Label"]'
XPATH_DC_CUUP_gNBIdCA_Title_Label = '//*[@id="DC_CUUP_gNBIdCA_Title_Label"]'
XPATH_DC_SummaryDetails = '//*[@id="DC_SummaryDetails"]/div[1]/div/div[1]'
XPATH_DC_gNBIdTitle_Label = '//*[@id="DC_gNBIdTitle_Label"]'
XPATH_DC_gNBId_Value_Label = '//*[@id="DC_gNBId_Value_Label"]'
XPATH_DC_cucp_gNBNameTitle_Label = '//*[@id="DC_cucp_gNBNameTitle_Label"]'
XPATH_DC_cucp_gNBName_Value_Label = '//*[@id="DC_cucp_gNBName_Value_Label"]'
XPATH_DC_CUUP_gNBIdTitle_Label = '//*[@id="DC_CUUP_gNBIdTitle_Label"]'
XPATH_DC_CUUP_gNBId_Value_Label = '//*[@id="DC_CUUP_gNBId_Value_Label"]'
XPATH_DC_cuup_gNBNameTitle_Label = '//*[@id="DC_cuup_gNBNameTitle_Label"]'
XPATH_DC_cuup_gNBName_Value_Label = '//*[@id="DC_cuup_gNBName_Value_Label"]'
XPATH_DC_gNBNameTitle_Label = '//*[@id="DC_gNBNameTitle_Label"]'
XPATH_DC_gNBName_Value_Label = '//*[@id="DC_gNBName_Value_Label"]'
ID_DC_NetCnfSessionStatusCA_Title_Label = 'id=DC_NetCnfSessionStatusCA_Title_Label'
ID_DC_HeartBeatStatusCA_Title_Label = 'id=DC_HeartBeatStatusCA_Title_Label'
ID_DC_DvcAlarmsCountCA_Title_Label = 'id=DC_DvcAlarmsCountCA_Title_Label'
ID_DC_Provision_Status_Count_Display_Name = 'id=DC_Provision_Status_Count_Display_Name'
ID_DC_CUUP_gNBId_Value_Label = 'id=DC_CUUP_gNBId_Value_Label'
ID_DC_NetCnfSessionStatus_Value_Label = 'id=DC_NetCnfSessionStatus_Value_Label'
ID_DC_HeartBeatStatus_Value_Label = 'id=DC_HeartBeatStatus_Value_Label'
XPATH_Number_of_Critical_Alarm = '//*[@id="alarmValue"]/div[1]/div'
XPATH_Number_of_Major_Alarm = '//*[@id="alarmValue"]/div[3]/div'
XPATH_Number_of_Minor_Alarm = '//*[@id="alarmValue"]/div[5]/div'
XPATH_Number_of_Warning_Alarm = '//*[@id="alarmValue"]/div[7]/div'
XPATH_Number_of_Failed_Provisioned = '//*[@id="DC_Provision_Status_Count_HLayout"]/div[1]/div'
XPATH_Number_of_Delta_Provisioned = '//*[@id="DC_Provision_Status_Count_HLayout"]/div[3]/div'
XPATH_Number_of_Running_Provisioned = '//*[@id="DC_Provision_Status_Count_HLayout"]/div[5]/div'
XPATH_Number_of_Pending_Provisioned = '//*[@id="DC_Provision_Status_Count_HLayout"]/div[7]/div'
ID_DC_DashBoard_ConnectivityDetails_Title = 'id=DC_DashBoard_ConnectivityDetails_Title'
ID_DC_DashBoard_NetConfDetails_Title = 'id=DC_DashBoard_NetConfDetails_Title'
ID_DC_LocalIPAddressTitle_Label = 'id=DC_LocalIPAddressTitle_Label'
ID_DC_LocalIPAddress_Value_Label = 'id=DC_LocalIPAddress_Value_Label'
ID_DC_FirstEstSessTime_Title_Label = 'id=DC_FirstEstSessTime _Title_Label'
ID_DC_FirstEstSessTime_Value_Label = 'id=DC_FirstEstSessTime_Value_Label'
ID_DC_LastEstSessTime_Title_Label = 'id=DC_LastEstSessTime _Title_Label'
ID_DC_LastEstSessTime_Value_Label = 'id=DC_LastEstSessTime_Value_Label'
ID_DC_NextSessRetryTime_Title_Label = 'id=DC_NextSessRetryTime _Title_Label'
ID_DC_NextSessRetryTime_Value_Label = 'id=DC_NextSessRetryTime_Value_Label'
ID_DC_LastSessRetryTime_Title_Label = 'id=DC_LastSessRetryTime _Title_Label'
ID_DC_LastSessRetryTime_Value_Label = 'id=DC_LastSessRetryTime_Value_Label'
ID_DC_DashBoard_VESHtBeatDetails_Title = 'id=DC_DashBoard_VESHtBeatDetails_Title'
ID_DC_FirstReceviedTime_Title_Label = 'id=DC_FirstReceviedTime _Title_Label'
ID_DC_FirstReceviedTime_Value_Label = 'id=DC_FirstReceviedTime_Value_Label'
ID_DC_LastReceviedTime_Title_Label = 'id=DC_LastReceviedTime _Title_Label'
ID_DC_LastReceviedTime_Value_Label = 'id=DC_LastReceviedTime_Value_Label'
ID_DC_HeartBeatIntervalCA_Title_Label = 'id=DC_HeartBeatIntervalCA_Title_Label'
ID_DC_HeartBeatInterval_Value_Label = 'id=DC_HeartBeatInterval_Value_Label'
ID_DC_HeartBeatMissingCountCA_Title_Label = 'id=DC_HeartBeatMissingCountCA_Title_Label'
ID_DC_HeartBeatMissingCount_Value_Label = 'id=DC_HeartBeatMissingCount_Value_Label'
ID_DC_DashBoard_Map_Title = 'id=DC_DashBoard_Map_Title'
ID_DC_cuUserPlaneCA_Title_Label = 'id=DC_cuUserPlaneCA_Title_Label'
XPATH_DC_cuUserPlaneCA_Title_Value = '//*[@id="deviceAssocLyt"]/div[1]'
ID_DC_distributedUnitCA_Title_Label = 'id=DC_distributedUnitCA_Title_Label'
XPATH_DC_distributedUnitCA_Title_Value = '//*[@id="deviceAssocLyt"]/div[1]'
ID_DC_cuControlPlaneCA_Title_Label = 'id=DC_cuControlPlaneCA_Title_Label'
XPATH_DC_cuControlPlaneCA_Title_Value = '//*[@id="deviceAssocLyt"]/div[1]'
ID_DC_CPUP_Rp_Status_Count_Display_Name = 'id=DC_DU_CPUP_Rp_Status_Count_Display_Name'
XPATH_DC_DU_CPUP_Rp_Status_Count_Display_Value = '//*[@id="value"]'
ID_DC_DU_CPUP_Rp_Status_Count_Display_Name = 'id=DC_DU_Rp_Status_Count_Display_Name'
ID_DC_DashBoard_DeviceDetails_Title = 'id=DC_DashBoard_DeviceDetails_Title'
ID_userTag_title = 'id=userTag_title'
ID_DC_SoftwareVersionCA_Title_Label = 'id=DC_SoftwareVersionCA_Title_Label'
ID_DC_SoftwareVersion_Value_Label = 'id=DC_SoftwareVersion_Value_Label'
ID_DC_FirstActivationTime_Title_Label = 'id=DC_FirstActivationTime _Title_Label'
ID_DC_FirstActivationTime_Value_Label = 'id=DC_FirstActivationTime_Value_Label'
ID_DC_lastBoot_Time_Title_Label = 'id=DC_lastBoot_Time _Title_Label'
ID_DC_lastBoot_Time_Value_Label = 'id=DC_lastBoot_Time_Value_Label'
ID_DC_LastActivationTime_Title_Label = 'id=DC_LastActivationTime _Title_Label'
ID_DC_LastActivationTime_Value_Label = 'id=DC_LastActivationTime_Value_Label'
ID_DC_DashBoard_ConfigurationDetails_Title = 'id=DC_DashBoard_ConfigurationDetails_Title'
ID_remoteAddrCA_Title_Label = 'id=DC_EPE1.remoteAddrCA_Title_Label'
ID_remoteAddr_Value_Label = 'id=DC_EPE1.remoteAddr_Value_Label'
ID_stateCA_Title_Label = 'id=DC_EPE1.stateCA_Title_Label'
ID_state_Value_Label = 'id=DC_EPE1.state_Value_Label'
ID_DC_Dashboard_Device_History = 'id=DC_Dashboard_Device_History'
ID_DC_Dashboard_Devicepnpstatus = 'id=DC_Dashboard_Devicepnpstatus'
ID_DC_DashBoard_Sector_Status_Title = 'id=DC_DashBoard_Sector_Status_Title'
XPATH_X2_CONNECTION_ID_Title = '//*[@id="DC_Dashboard_SectorStatus"]/div[2]/div[1]/div/div[1]/div'
#XPATH_DC_Dashboard_DUCellInuse_EPX2C = '//*[@id="DC_Dashboard_DUCellInuse_EPX2C.id"]'
XPATH_DC_Dashboard_DUCellInuse_EPX2C = '//*[@id="DC_Dashboard_SectorStatus"]/div[2]/div[2]/div/div[1]/div'
XPATH_X2_IP_Address = '//div[contains(text(),"X2 IP Address")]'
XPATH_DC_Dashboard_DUCellInuse_EPX2C_remoteAddr = '//*[@id="DC_Dashboard_SectorStatus"]/div[2]/div[2]/div/div[2]/div'
XPATH_X2_Connection_Status_Title = '//div[contains(text(),"X2 Connection Status")]'
XPATH_X2_Connection_Status_Value = '//*[@id="DC_Dashboard_SectorStatus"]/div[2]/div[2]/div/div[3]/div'
XPATH_Associated_BC = '//div[contains(text(),"Associated Baseband Controller: MAC ID / Service S")]'
XPATH_DMS_BC_MAIN_DATA = '//*[@id="DC_Dashboard_SectorStatus"]/div[2]/div[2]/div/div[4]/div'
ID_DC_DashBoard_DUCellInuse_Status_Title = 'id=DC_DashBoard_DUCellInuse_Status_Title'
XPATH_DC_DashBoard_DUCellInuse_Status = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[1]/div/div[1]/div'
XPATH_CELL_DETAILS_STATUS_CELL1 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[2]/div/div[1]/div'
XPATH_CELL_DETAILS_STATUS_CELL2 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[3]/div/div[1]/div'
XPATH_CELL_DETAILS_STATUS_CELL3 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[4]/div/div[1]/div'
XPATH_CELL_DETAILS_STATUS_CELL4 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[5]/div/div[1]/div'
XPATH_DC_DashBoard_DUCellInuse_Prov_Title = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[1]/div/div[2]/div'
XPATH_CELL_DETAILS_Provisioning_CELL1 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[2]/div/div[2]/div'
XPATH_CELL_DETAILS_Provisioning_CELL2 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[3]/div/div[2]/div'
XPATH_CELL_DETAILS_Provisioning_CELL3 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[4]/div/div[2]/div'
XPATH_CELL_DETAILS_Provisioning_CELL4 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[4]/div/div[2]/div'
XPATH_DC_DashBoard_DUCellInuse_Administrative_Title = '//div[contains(text(),"Administrative")]'
XPATH_CELL_DETAILS_Administrative_CELL1 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[2]/div/div[3]/div'
XPATH_CELL_DETAILS_Administrative_CELL2 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[3]/div/div[3]/div'
XPATH_CELL_DETAILS_Administrative_CELL3 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[4]/div/div[3]/div'
XPATH_CELL_DETAILS_Administrative_CELL4 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[5]/div/div[3]/div'
XPATH_DC_DashBoard_DUCellInuse_Operational_Title = '//div[contains(text(),"Operational")]'
XPATH_CELL_DETAILS_Operational_CELL1 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[2]/div/div[4]/div'
XPATH_CELL_DETAILS_Operational_CELL2 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[3]/div/div[4]/div'
XPATH_CELL_DETAILS_Operational_CELL3 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[4]/div/div[4]/div'
XPATH_CELL_DETAILS_Operational_CELL4 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[5]/div/div[4]/div'
XPATH_DC_DashBoard_DUCellInuse_Cell_State_Title = '//div[contains(text(),"Cell State")]'
XPATH_CELL_DETAILS_Cell_State_CELL1 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[2]/div/div[5]/div'
XPATH_CELL_DETAILS_Cell_State_CELL2 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[3]/div/div[5]/div'
XPATH_CELL_DETAILS_Cell_State_CELL3 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[4]/div/div[5]/div'
XPATH_CELL_DETAILS_Cell_State_CELL4 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[5]/div/div[5]/div'
XPATH_DC_DashBoard_DUCellInuse_Total_RPs_Title = '//div[contains(text(),"Total RPs / RP In Service")]'
XPATH_CELL_DETAILS_Total_RPs_CELL1 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[2]/div/div[6]/div'
XPATH_CELL_DETAILS_Total_RPs_CELL2 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[3]/div/div[6]/div'
XPATH_CELL_DETAILS_Total_RPs_CELL3 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[4]/div/div[6]/div'
XPATH_CELL_DETAILS_Total_RPs_CELL4 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[5]/div/div[6]/div'
XPATH_DC_Dashboard_DUCellInuse_nRPCI = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[1]/div/div[7]/div'
XPATH_CELL_DETAILS_nRPCI_CELL1 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[2]/div/div[7]/div'
XPATH_CELL_DETAILS_nRPCI_CELL2 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[3]/div/div[7]/div'
XPATH_CELL_DETAILS_nRPCI_CELL3 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[4]/div/div[7]/div'
XPATH_CELL_DETAILS_nRPCI_CELL4 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[5]/div/div[7]/div'
XPATH_DC_DashBoard_DUCellInuse_RSI_Title = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[1]/div/div[8]/div'
XPATH_CELL_DETAILS_Root_Sequence_Index_CELL1 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[2]/div/div[7]/div'
XPATH_CELL_DETAILS_Root_Sequence_Index_CELL2 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[3]/div/div[7]/div'
XPATH_CELL_DETAILS_Root_Sequence_Index_CELL3 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[4]/div/div[7]/div'
XPATH_CELL_DETAILS_Root_Sequence_Index_CELL4 = '//*[@id="DC_Dashboard_DUCellInuseStatus"]/div[2]/div[5]/div/div[7]/div'
ID_CELL_DETAILS_DUConfig_F1_C_Address = 'id=DC_EPF1C.remoteAddrCA_Title_Label'
ID_CELL_DETAILS_DUConfig_F1_C_Value = 'id=DC_EPF1C.remoteAddr_Value_Label'
ID_DC_Prov_Cell_Configuration_Title = 'id=DC_DashBoard_DUConfig_Status_Title'
XPATH_DC_Prov_Cell_Config_Parameters = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[1]/div/div[1]/div'
XPATH_Prov_Cell_Config_Parameters_CELL1 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[2]/div/div[1]/div'
XPATH_Prov_Cell_Config_Parameters_CELL2 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[3]/div/div[1]/div'
XPATH_Prov_Cell_Config_Parameters_CELL3 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[4]/div/div[1]/div'
XPATH_Prov_Cell_Config_Parameters_CELL4 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[5]/div/div[1]/div'
XPATH_Prov_Cell_Config_NR_PCI = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[1]/div/div[2]/div'
XPATH_Prov_Cell_Config_NR_PCI_CELL1 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[2]/div/div[2]/div'
XPATH_Prov_Cell_Config_NR_PCI_CELL2 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[3]/div/div[2]/div'
XPATH_Prov_Cell_Config_NR_PCI_CELL3 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[4]/div/div[2]/div'
XPATH_Prov_Cell_Config_NR_PCI_CELL4 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[5]/div/div[2]/div'
XPATH_Prov_Cell_Config_ARFCN_DL_Title = '//div[contains(text(),"ARFCN DL")]'
XPATH_Prov_Cell_Config_ARFCN_DL_CELL1 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[2]/div/div[3]/div'
XPATH_Prov_Cell_Config_ARFCN_DL_CELL2 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[3]/div/div[3]/div'
XPATH_Prov_Cell_Config_ARFCN_DL_CELL3 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[4]/div/div[3]/div'
XPATH_Prov_Cell_Config_ARFCN_DL_CELL4 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[5]/div/div[3]/div'
XPATH_Prov_Cell_Config_ARFCN_UL_Title = '//div[contains(text(),"ARFCN UL")]'
XPATH_Prov_Cell_Config_ARFCN_UL_CELL1 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[2]/div/div[4]/div'
XPATH_Prov_Cell_Config_ARFCN_UL_CELL2 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[3]/div/div[4]/div'
XPATH_Prov_Cell_Config_ARFCN_UL_CELL3 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[4]/div/div[4]/div'
XPATH_Prov_Cell_Config_ARFCN_UL_CELL4 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[5]/div/div[4]/div'
XPATH_Prov_Cell_Config_DL_BS_Channel_BW_Title = '//div[contains(text(),"DL BS Channel BW")]'
XPATH_Prov_Cell_Config_DL_BS_Channel_BW_CELL1 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[2]/div/div[5]/div'
XPATH_Prov_Cell_Config_DL_BS_Channel_BW_CELL2 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[3]/div/div[5]/div'
XPATH_Prov_Cell_Config_DL_BS_Channel_BW_CELL3 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[4]/div/div[5]/div'
XPATH_Prov_Cell_Config_DL_BS_Channel_BW_CELL4 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[5]/div/div[5]/div'
XPATH_Prov_Cell_Config_UL_BS_Channel_BW_Title = '//div[contains(text(),"UL BS Channel BW")]'
XPATH_Prov_Cell_Config_UL_BS_Channel_BW_CELL1 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[2]/div/div[6]/div'
XPATH_Prov_Cell_Config_UL_BS_Channel_BW_CELL2 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[3]/div/div[6]/div'
XPATH_Prov_Cell_Config_UL_BS_Channel_BW_CELL3 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[4]/div/div[6]/div'
XPATH_Prov_Cell_Config_UL_BS_Channel_BW_CELL4 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[5]/div/div[6]/div'
XPATH_Prov_Cell_Config_NR_Freq_Band_DL = '//div[contains(text(),"NR Frequency Band DL")]'
XPATH_Prov_Cell_Config_NR_Freq_Band_DL_CELL1 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[2]/div/div[7]/div'
XPATH_Prov_Cell_Config_NR_Freq_Band_DL_CELL2 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[3]/div/div[7]/div'
XPATH_Prov_Cell_Config_NR_Freq_Band_DL_CELL3 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[4]/div/div[7]/div'
XPATH_Prov_Cell_Config_NR_Freq_Band_DL_CELL4 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[5]/div/div[7]/div'
XPATH_Prov_Cell_Config_Root_Sequence_Index_Title = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[1]/div/div[8]/div'
XPATH_Prov_Cell_Config_Root_Sequence_Index_CELL1 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[2]/div/div[8]/div'
XPATH_Prov_Cell_Config_Root_Sequence_Index_CELL2 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[3]/div/div[8]/div'
XPATH_Prov_Cell_Config_Root_Sequence_Index_CELL3 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[4]/div/div[8]/div'
XPATH_Prov_Cell_Config_Root_Sequence_Index_CELL4 = '//*[@id="DC_Dashboard_DUConfigStatus"]/div[2]/div[5]/div/div[8]/div'

XPATH_WARNING_ICON = '//body/div[@id="deviceconsole-1831658943"]/div[1]/div[2]/div[4]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/img[1]'
WARNING_REASON = 'Some of the X2 connections are in non operational mode'