# Dashboard Page
ID_DASHBOARD_DASHBOARD_BUTTON = 'id=DC_Menu_Content_Dashboard_Button'
#XPATH_DMS_INSERVICE_TAG = '//div[contains(@class,"dms-summary-inservice")]'
XPATH_DMS_INSERVICE_TAG = '//div[contains(@class,"dms-summary-inservice-sector")]'
ID_DASHBOARD_LAST_CONTACT_TIME = 'id=DC_LastContactTime_Value_Label'
XPATH_DASHBOARD_CONNECT_DEVICE = '//div[contains(@class,"v-csslayout-per-device-action-connect")]'
XPATH_DASHBOARD_REBOOT_DEVICE = '//div[contains(@class,"v-csslayout-per-device-action-reboot")]'
XPATH_DASHBOARD_REPLAN_DEVICE = '//div[contains(@class,"v-csslayout-per-device-action-replan")]'
ID_DASHBOARD_HEADER_STRING = 'id=DC_Dashboard_Header'
XPATH_DASHBOARD_REFRESH_PLAY_PAUSE_BUTTON = '//button[@id="DC_Refresh_PlayPauseButton"]'
XPATH_DEVICE_ACTION_POPUP_OK = '//span[text()="Ok"]'
DEVICE_DASHBOARD_DEVICE_URL = '{dms_device_console}#!mv/dashboard/?srchKey=MAC&id={device_macid}&dt=ONECELL5GDU&context=null'
XPATH_MANAGED_BUTTON='//*[@id="ManageOrUnManage"]'
XPATH_MANAGED_CONFIRM_BUTTON='//*[@id="DC_Confirm_Window_Confirm_Button"]'
XPATH_INPUT_UNMANAGED_MANAGED='//*[@id="DC_ManageOrUnmanage_Window_Content"]/div[3]/div/div[2]/textarea'
XPATH_NETCONF_CONNECTION_STATUS='//*[@id="DC_NetCnfSessionStatus_Value_Label"]'
