Device_alarm_comment_button = 'id=NC_ALARM_ONLY_ACTIVE_DEVICE_ALARM_ACTION_ANNOTATION'
Device_alarm_comment_commentbox = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[3]/textarea[1]'
Device_alarm_comment_confirm = 'id=Annotation_Submit_Button'
ID_APPLY_FILTER = 'id=DeviceAlarms_AppyFilterButton'
Header_Checkbox = 'id=headerCheckBox'
Device_Alarm_ACK = 'id=NC_ALARM_ONLY_ACTIVE_DEVICE_ALARM_ACTION_ACKNOWLEDGE'
Device_Alarm_ACK_Comment = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[5]/textarea[1]'
Device_Alarm_ACK_Confirm = 'id=NC_DEVICE_ALARM_ACTION_ACKNOWLEDGE_Submit_Button'
Device_Alarm_UnACK = 'id=NC_ALARM_ONLY_ACTIVE_DEVICE_ALARM_ACTION_UNACKNOWLEDGE'
Device_Alarm_UnACK_Comment = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[5]/textarea[1]'
Device_Alarm_UnACK_Confirm = 'id=NC_DEVICE_ALARM_ACTION_UNACKNOWLEDGE_Submit_Button'
Device_Alarm_Clear = 'id=NC_ALARM_ONLY_ACTIVE_DEVICE_ALARM_ACTION_CLEAR'
Device_Alarm_Clear_Comment = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[5]/textarea[1]'
Device_Alarm_Clear_Confirm = 'id=NC_DEVICE_ALARM_ACTION_CLEAR_Submit_Button'
Device_Alarm_Delete = 'id=NC_ALARM_ONLY_ACTIVE_DEVICE_ALARM_ACTION_DELETE'
Device_Alarm_Delete_Confirm ='id=NC_DEVICE_ALARM_ACTION_DELETE_Submit_Button'
proable_cause_device='//*[@id="DC_DeviceAlarms_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[6]/div/input'
source='//*[@id="DC_DeviceAlarms_FilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[8]/div/input'
