DEVICE_FILE_IMPORT='//*[@id="NC_FileImport_FileName"]/div'
DEVICE_FILE_TYPE_BUTTON='//*[@id="NC_FileImport_FileTypes"]/div'
SELECT_SERVICE_SETTING_FILE='//span[contains(text(),"Service Settings")]'
SELECT_NETCONF_MOUNT_FILE='//span[contains(text(),"Netconf Mount File")]'
SELECT_ENTITY_MAPPING_FILE='//span[contains(text(),"Entity Mapping File")]'
FOLDER_BUTTON='//*[@id="DMS_FOLDER_OPEN_DEBUG_ID"]'
UPLOAD_OK_BUTTON='//*[@id="NC_FileImport_Upload"]'
IMPORT_BUTTON='//*[@id="NC_FileImport_ImportButton"]'
OPERTION_HISTORY_BUTTON='//*[@id="NC_DMSHeader_Operation_History_Button"]'
#OPERTION_HISTORY_RESOURCE_NAME='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[4]/div'
#OPERTION_HISTORY_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[5]/div'
#OPERTION_HISTORY_OPERATION_STATUS='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[6]/div'
OPERTION_HISTORY_RESOURCE_NAME='//*[@id="DMS_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[4]/div'
OPERTION_HISTORY_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[5]/div'
OPERTION_HISTORY_OPERATION_STATUS='//*[@id="DMS_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[6]/div'


SHOW_ADVANCE_OPTION='//*[@id="showAdvanceBtn"]'
PRO_ASSOCIATION_INPUT='//*[@id="existingProAssoTable"]/div[2]/div/div/div[2]/input'
APPLY_FILTER='//*[@id="applyFilterBtn"]'
ADD_BUTTON='//*[@id="addButton"]'
SAVE_BUTTON='//*[@id="DC_Device_Config_Save_Button"]'
SELECT_CHECKBOX='//*[@id="existingProAssoTable"]/div[3]/div[1]/table/tbody/tr/td[1]'
XPATH_DELETE_CHECKBOX='//*[@id="headerCheckBox"]'
XPATH_DELETE_BUTTON='//*[@id="deleteBtn"]'
XPATH_ADD_BUTTON='//*[@id="addNewBtn"]'
XPATH_PROFILE_ASSOCIATIOn_BUTTON_CLICK='//*[@id="ProfileAssociation.ServiceArea"]/div[2]/div'
XPATH_CHOOSE_FILE='//*[@id="SS_FileUpload"]'
XPATH_CLICK_OK_BUTTON='//*[@id="DC_FileUpload_OkBtn"]'
XPATH_ORP_PARAM_SAVE_BUTTON = '//*[@id="DC_Device_Config_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP = '//*[contains(text(),"Saved successfully")]'


SELECT_FACTORY_FILE='//span[contains(text(),"Factory File")]'
#XPATH_OH_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[2]/div/div/div[5]/input'
XPATH_OH_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[1]/div[1]/div/table/tbody/tr[2]/td[5]/div/input'
ID_OH_APPLY_BUTTON='//*[@id="DC_OperationHistory_ApplyFilter_Button"]'
SELECT_GSV_FILE='//span[contains(text(),"Gold Standard Value File")]'
SELECT_OmKPi_FILE='//span[contains(text(),"OmKpi File")]'

XPATH_OPERATION_TYPE_NEW = '//tbody/tr[2]/td[5]/div[1]/input[1]'
#XPATH_OH_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[1]/div[1]/div/table/tbody/tr[2]/td[5]/div/input'
#OPERTION_HISTORY_RESOURCE_NAME='//*[@id="DMS_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[4]/div'
#OPERTION_HISTORY_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[5]/div'
#OPERTION_HISTORY_OPERATION_STATUS='//*[@id="DMS_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[6]/div'
XPATH_FIRST_ESTABLISHMENT_VALUE = '//div[@id="DC_FirstEstSessTime_Value_Label"]'
XPATH_LAST_ESTABLISHMENT_VALUE = '//div[@id="DC_LastEstSessTime_Value_Label"]'
XPATH_HEARTBEAT_STATUS = '//div[@id="DC_HeartBeatStatus_Value_Label"]'
XPATH_VNF_MANAGED_STATE = '//div[@id="DC_MaintenanceStatus"]'
XPATH_DEVICE_HISTORY_DETAILS = '//body[1]/div[1]/div[1]/div[2]/div[4]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[1]'
XPATH_DH_DETAILS_TEXT = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[3]'
XPATH_DU_DH_DETAILS = '//body[1]/div[2]/div[3]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[4]'

XPATH_EDIT_ENTITY_MAPPING = '//tbody/tr[6]/td[7]/div[1]/div[1]/div[1]/button[1]'
EDIT_SCHEDULE_TIME = '//div[@id="NC_ScheduleImport_StartDateField"]/input'
XPATH_SCHEDULE_SAVE_BUTTON = '//*[@id="NC_ScheduleImport_Save"]/span'
XPATH_CLICK = '//*[@id="NC_ScheduleImport_Edit Schedule"]/div/div/div[3]/div/div/div[1]/div/div[9]/div/div/div'
XPATH_ODF_EDIT_BUTTON = '//tbody/tr[8]/td[7]/div[1]/div[1]/div[1]/button[1]'

XPATH_OPERATION_HISTORY_RESOURCE = '//*[@id="DMS_Operation_History_Table"]/div[1]/div[1]/div/table/tbody/tr[2]/td[4]/div/input'
XPATH_APPLY_FILTER_RESOURCE = '//*[@id="DC_OperationHistory_ApplyFilter_Button"]/span'

XPATH_DEVICE_STATE = '//div[@id="DC_SummarySerStatus"]'
OPERTION_HISTORY_METHOD = '//*[@id="DMS_Operation_History_Table"]/div[2]/div[1]/table/tbody/tr[1]/td[3]/div'
GSV_IMPORT_EDIT_BUTTON = '//tbody/tr[1]/td[7]/div[1]/div[1]/div[1]/button[1]'