DEVICE_LIST_PAGE_URL = '//*[@id="DeviceList"]/div[2]'
XPATH_DEVICE_LIST_SHOW_SEARCH_OPTIONS = '//*[@id="NC_DeviceList_AdvancedSearch"]'
XPATH_SELECT_DEVICE_TYPE = '//*[@id="NC_DeviceList_DeviceType"]/input'
XPATH_SELECT_DEVICE_TYPE1 = '/body/div[1]/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[1]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div[1]/div/div/div[3]/div/div'
XPATH_FILTER_NAME = '//*[@id="NC_DeviceList_FilterName"]'
XPATH_DEVICE_FILTER_LIST_INPUT = '//*[@id="NC_DeviceList_ColumnSelector"]/input'
XPATH_DEVICE_TYPE_SELECT = '//*[@id="NC_DeviceList_DeviceType"]/div'
#XPATH_SELECT_DEVICE_TYPE = '//body/div[@id="networkconsole-1878154089"]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]'
XPATH_SELECT_DEVICE_TYPE_ALL = '//span[contains(text(),"All Device Types")]'
XPATH_DEVICE_ONECELL = '//span[contains(text(),"0005B9-LTE_Enterprise_C-RANSC_Cntrl")]'
XPATH_DEVICE_NGRP = '//span[contains(text(),"0005B9-LTE_Enterprise_C-RANSC_NGRadio")]'
XPATH_DEVICE_CGRP = '//span[contains(text(),"0005B9-LTE_Enterprise_C-RANSC_Radio")]'
#XPATH_DEVICE_NGRF = '//span[contains(text(),"0005B9-LTE_Enterprise_C-RANSC_NGRadio_RFModule")]'
XPATH_DEVICE_NGRF = '//span[contains(text(),"0005B9-CS_ONECELL_RU51_RFModule")]'
XPATH_BC_MACID = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[2]/td/span'
XPATH_NGRADIO_DROPDOWN = '//*[@id="NC_DeviceList_ColumnSelector"]/div'
XPATH_RFMODULE_ID = '//span[contains(text(),"RF Module ID")]'
#XPATH_NGRADIO_RFMODULE = '//span[contains(text(),"0005B9-LTE_Enterprise_C-RANSC_NGRadio_RFModule")]'
XPATH_NGRADIO_RFMODULE = '//span[contains(text(),"0005B9-CS_ONECELL_RU51_RFModule")]'
XPATH_FILTER_INPUT = '//*[@id="NC_DeviceList_ColumnSelector"]/div'
XPATH_MACID = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[1]/td/span'
id_for_serial = 'id=NC_DeviceList_ColumnSelector'
XPATH_FACTORY_SERIAL = '//span[contains(text(),"Factory Serial Number")]'
XPATH_SOFTWARE_VERSION = '//span[contains(text(),"Software Version")]'
XPATH_GREATER_THAN = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[4]/td/span'
XPATH_GREATER_THAN_EQUAL = '//span[contains(text(),"GREATER_THAN_EQUAL")]'
XPATH_ENODEB_NAME = '//span[contains(text(),"eNodeB Name")]'
XPATH_VENUE_NAME = '//span[contains(text(),"Venue Name")]'
XPATH_EXPRESSION_VALUE = '//*[@id="NC_DeviceList_UserOption"]'
XPATH_EXPRESSION_VALUE1 = '//body/div[@id="networkconsole-1878154089"]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[5]/div[1]/div[1]/div[5]/input[1]'
#XPATH_DROPDOWN = '//*[@id="NC_DeviceList_OperatorSelector"]/div'
XPATH_DROPDOWN = '//body/div[@id="networkconsole-1878154089"]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[5]/div[1]/div[1]/div[3]/div[1]/div[1]'
#XPATH_DROPDOWN = '//*[@id="NC_DeviceList_ColumnSelector"]'
#id_dropdown = 'id=NC_DeviceList_OperatorSelector'
XPATH_CREATE_FILTER_BUTTON = '//*[@id="NC_DeviceList_CreateFilter"]/span'
XPATH_MANAGE_FILTER_BUTTON = '//tbody/tr[1]/td[2]/div[1]/div[1]/div[1]'
#XPATH_ENTER_FILTER_NAME = '//body[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/input[1]'
#XPATH_ENTER_FILTER_NAME = '//*[@id="NC_DeviceList_FilterName"]'
XPATH_EDIT_FILTER_BUTTON = '//*[@id="NC_DeviceList_EditButton"]/div/div/div'
#id_for_filter = 'id= networkconsole-1878154089'
#id_for_contains = 'id=NC_DeviceList_OperatorSelector'
XPATH_PLUS_SIGN = '//*[@id="NC_DeviceList_UITableAddButton"]/div/div/div/span/i'
XPATH_GREATER = '//body/div[1]/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[1]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div[3]/div/div[2]/div/div[7]/div/div/div[3]/div/div'
#XPATH_MACID_SELECTOR = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[3]'
XPATH_GREATER1 = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[5]/td/span'
XPATH_VALUE = '//body/div[1]/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[1]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div[3]/div/div[2]/div/div[7]/div/div/div[5]/input'
XPATH_MACID_SELECT = '//body/div[1]/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[1]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div[3]/div/div[2]/div/div[7]/div/div/div[1]/div/div'
#XPATH_MACID_BUTTON = '//*[@id="NC_DeviceList_ColumnSelector"]/div'
XPATH_VENUE_EXPRESSION_VALUE = '//body/div[1]/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[1]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div[3]/div/div[2]/div/div/div/div/div[5]/input'
XPATH_DROPDOWN1 = '//body/div[2]/div[2]/div/div[3]'
XPATH_SAVE_BUTTON = '//body/div[1]/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[1]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div[5]/div/div/div[1]/button/span'
XPATH_FILTER_APPLY = '//body/div[1]/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[1]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div[3]/div[1]/table/tbody/tr/td[3]/div/div/div[1]/div/div/div/div'
XPATH_EXPRESSION_EDIT = '//body/div[1]/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[1]/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]/div/div[3]/div/div[2]/div/div[5]/div/div/div[5]/input'
XPATH_CONTAINS = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[3]/td'
XPATH_EQUALS_DROPDOWN = '//*[@id="NC_DeviceList_OperatorSelector"]/div'
XPATH_EQUALS = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[1]/td'
XPATH_NEXT_BUTTON = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[3]'
XPATH_NEXT_BUTTON1 = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[3]'
XPATH_NEXT_BUTTON2 = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[3]'
XPATH_FRIENDLY = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[4]/td/span'
#id_for_CONTAINS = 'id=VAADIN_COMBOBOX_OPTIONLIST'
XPATH_APPLY_FILTER = '//*[@id="DeviceList_AppyFilterButton"]/span'
XPATH_CREATE_APPLY = '//*[@id="NC_DeviceList_CreateAndApply"]/span'
XPATH_DELETE_BUTTON = '//*[@id="NC_DeviceList_DeleteButton"]/div/div/div'
XPATH_CONFIRM_DELETE = '//*[@id="NC_DeviceList_YesButton"]/span'
XPATH_APPLY_FILTER_BUTTON = '//button[*[contains(text(), "Apply Filter")]]'
XPATH_APPLY_FILTER_OPTION = '//*[@id="NC_DeviceList_ApplyFilterButton"]/div/div/div'
XPATH_CREATE_FILTER_SUCCESS_MSG = '//*[@id="networkconsole-1878154089"]/div/div[2]/div[4]/div/div/div/div/div[1]'
XPATH_GET_SUCCESS_TEXT= '//*[@id="networkconsole-1878154089"]/div/div[2]/div[4]/div/div'
#XPATH_DELETE_FILTER_SUCESSS_MSG = '//*[@id="networkconsole-1878154089"]/div/div[2]/div[4]/div/div/div/div/div[2]'
XPATH_EDIT_FILTER_SUCCESS_MSG = '//*[@id="networkconsole-1878154089"]/div/div[2]/div[4]/div/div/div/div/div[2]'
XPATH_MINUS_SIGN = '//body/div[@id="networkconsole-1878154089"]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[7]/div[1]/div[1]/div[11]/div[1]/div[1]/div[1]/div[1]/span[1]/i[1]'
XPATH_MINUS = '//body/div[@id="networkconsole-1878154089"]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[11]/div[1]/div[1]/div[1]/div[1]/span[1]/i[1]'
XPATH_FILTER_CRITERIA = '//body/div[@id="networkconsole-1878154089"]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/input[1]'
XPATH_FILTER_NAME_CRITERIA = '//tbody/tr[2]/td[1]/div[1]/input[1]'
XAPTH_LIST_ELEMENT='//span[contains(text(),"0005B9-LTE_Enterprise_C-RANSC_Radio")]'
XPATH_DEVICE_LIST_FILTER_COMBO='//*[@id="NC_DeviceList_DeviceType"]/input'
XPATH_FILTER_NAME_ADD = '//input[@id="NC_DeviceList_FilterName"]'
XPATH_FILTER_APPLY1 = '//tbody/tr[1]/td[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]'
XPATH_EDIT_AFTER_APPLY = '//tbody/tr[1]/td[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]'
XPATH_NEXT_ARROW = '//body[1]/div[2]/div[2]/div[1]/div[3]'

XPATH_DEVICE_CP = '//span[contains(text(),"0005B9-CS_ONECELL_CU-CP")]'
XPATH_DEVICE_UP = '//span[contains(text(),"0005B9-CS_ONECELL_CU-UP")]'
XPATH_DEVICE_DU = '//span[contains(text(),"0005B9-CS_ONECELL_DU")]'
XPATH_GNBID = '//span[contains(text(),"gNB ID")]'
XPATH_FILTER_CRITERIA1 = '//tbody/tr[2]/td[4]/div[1]/input[1]'
XPATH_APPLY_FILTER_LIST = '//span[contains(text(),"Apply Filter")]'
XPATH_SUCCESS_MSG = '//div[contains(text(),"Success")]'
XPATH_FILTER_CREATED_MSG = '//div[contains(text(),"Filter created successfully.")]'
XPATH_VENUE_NAME1 = '//div[contains(text(),"Automation_Venue")]'
XPATH_TABLE_ROW = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[2]'
XPATH_ENTER_FILTER_NAME = '//tbody/tr[2]/td[1]/div[1]/input[1]'

#XPATH_ENTER_FILTER_NAME = '//tbody/tr[2]/td[1]/div[1]/input[1]'
XPATH_NEXT_OPTION = '//body[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[7]/div[1]/div[1]/div[1]/div[1]/div[1]'
XPATH_NEXT1_OPTION = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[3]'
XPATH_CELLLOCALID = '//span[contains(text(),"Cell Local ID")]'
XPATH_DROPDOWN2 = '//body[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[7]/div[1]/div[1]/div[3]/div[1]/div[1]'
XPATH_ENTER_EXPRESSION2 = '//body[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[7]/div[1]/div[1]/div[5]/input[1]'
XPATH_MINUS2 = '//*[@id="NC_DeviceList_UITableDeleteButton"]/div/div/div/span/i'
XPATH_FILTER_APPLY_BUTTON = '//tbody/tr[1]/td[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]'
XPATH_REPLAN_STATUS = '//span[contains(text(),"Replan Status")]'
XPATH_NOT_EQUALS = '//span[contains(text(),"NOT_EQUALS")]'
XPATH_MINUS_UP = '//*[@id="NC_DeviceList_UITableDeleteButton"]/div/div/div/span/i'
XPATH_SOFTWARE_VERSIONDU = '//span[contains(text(),"Software Version")]'
XPATH_GREATER_THANEQUAL = '//span[contains(text(),"GREATER_THAN_EQUAL")]'
XPATH_ADD_DEVICE_BUTTON = '//span[contains(text(),"Add Device")]'
XPATH_VNFID_ENTER = '//*[@id="DC_MacIDOrSerialNo_TF"]'
XPATH_ENTER_IPADDRESS = '//*[@id="DC_IpV4OrIpV6OrHostname_TF"]'
XPATH_CP_PORT = '//*[@id="DC_Port_TF"]'
XPATH_CP_SOFTWARE_VERSION = '//*[@id="DC_swVersion_TF"]'
XPATH_USER = '//*[@id="DC_UserName_TF"]'
XPATH_PASSWORD = '//*[@id="password"]'
XPATH_CLICK = '//*[@id="NC_AddDeviceDetails_Window_Content"]/div[1]/div'
XPATH_CLICK_ENABLE = '//*[@id="NC_AddDeviceDetails_Window_Content"]/div[1]/div'
XPATH_ADD_SAVE = '//button[@id="NC_Save_Btn"]'
XPATH_SUCCESS = '//*[@id="networkconsole-1878154089-overlays"]/div[2]'
XPATH_ADD_MSG = '//*[@id="networkconsole-1878154089-overlays"]/div[2]'
XPATH_VNFID_SEARCH = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[2]/div/input'
XPATH_APPLY = '//*[@id="DeviceAlarms_AppyFilterButton"]/span'
XPATH_CHECKBOX = '//*[@id="gwt-uid-29"]'
XPATH_CHECKBOX1 = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[2]/div[1]/table/tbody/tr/td[1]/div/span'
XPATH_DELETE_DEVICE = '//*[@id="NC_Delete_APs_Button"]/span'
XPATH_CONFIRM_DELETE1 = '//*[@id="NC_Floor_Plan_CancelConfirmWindow"]/div/div/div[3]/div/div/div[2]/div/div[1]/button/span'
XPATH_DELETE_SUCCESS = 'CP_vnfid = "autotest-102cucp1"'
XPATH_DROPDOWN_LIST = '//*[@id="DC_Menu_Content_Get_Menu_Content_Page"]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div/div'
XPATH_UP_DEVICE = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[3]/td/span'
XPATH_DROPDOWN_SELECT = '//*[@id="NC_DeviceList_SavedFilterComponent"]/div'
XPATH_SELECT_FILTER = '//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[1]/td'
XPATH_MODE_DROPDOWN = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[3]/div/div/div'
XPATH_MODEUSER_UNMANAGED = '//span[contains(text(),"User Unmanaged")]'
XPATH_MANAGE_BUTTON = '//span[contains(text(),"Manage")]'
XPATH_APPLY_CONDITION = '//span[contains(text(),"Apply Filter")]'
XPATH_CONFIRM_MANAGE = '//span[contains(text(),"Confirm")]'
XPATH_MANAGED = '//span[contains(text(),"Managed")]'
XPATH_USER_UNAMANAGE = '//span[contains(text(),"User Unmanage")]'
XPATH_CONFIRM_UNMANAGE = '//span[contains(text(),"Confirm")]'

XPATH_INPUT_GNBID = '//*[@id="NC_DeviceList_PagedFilterTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[4]/div/input'
XPATH_CLICK_GNBID = '//*[@id="NC2051_Link"]/a'
XPATH_BC_MACID_ENTER = '//*[@id="DC_MacIDOrSerialNo_TF"]'
XPATH_SERIAL_NUMBER_ENTER = '//*[@id="DC_SerialNumber_TF"]'
XPATH_BC_PASSWORD_ENTER = '//*[@id="DC_Password_TF"]'
XPATH_PRODUCT_SKU = '//*[@id="DC_ProductSKU_TF"]'
XPATH_ADD_BC_MSG = '//*[@id="networkconsole-1878154089-overlays"]/div[2]/div/div/p'
XPATH_BC_SEARCH = '//tbody/tr[2]/td[2]/div[1]/input[1]'

XPATH_DEVICELIST_APPLY_FILTER = '//*[@id="DeviceList_AppyFilterButton"]/span'