DEVICE_FILE_IMPORT='//*[@id="NC_FileImport_FileName"]/div'
DEVICE_FILE_TYPE_BUTTON='//*[@id="NC_FileImport_FileTypes"]/div'
SELECT_SERVICE_SETTING_FILE='//span[contains(text(),"Service Settings")]'
FOLDER_BUTTON='//*[@id="DMS_FOLDER_OPEN_DEBUG_ID"]'
UPLOAD_OK_BUTTON='//*[@id="NC_FileImport_Upload"]'
IMPORT_BUTTON='//*[@id="NC_FileImport_ImportButton"]'
OPERTION_HISTORY_RESOURCE_NAME='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[4]/div'
OPERTION_HISTORY_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[5]/div'
OPERTION_HISTORY_OPERATION_STATUS='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[6]/div'
ODF_IMPORT_EDIT_BUTTON='//div[text()="ODF Import"]/../../td[7]/div/div/div[1]'
EDIT_SCHEDULE_TIME='//*[@id="NC_ScheduleImport_StartDateField"]/input'
SCHEDULE_IMPORT_SAVE_BUTTON='//*[@id="NC_ScheduleImport_Save"]'
Factory_IMPORT_EDIT_BUTTON='//div[text()="Factory Import"]/../../td[7]/div/div/div[1]'


SHOW_ADVANCE_OPTION='//*[@id="showAdvanceBtn"]'
#PRO_ASSOCIATION_INPUT='//*[@id="existingProAssoTable"]/div[2]/div/div/div[2]/input'
PROFILE_ASSOCIATION_INPUT='//*[@id="existingProAssoTable"]/div[1]/div[1]/div/table/tbody/tr[2]/td[2]/div/input'
APPLY_FILTER='//*[@id="applyFilterBtn"]'
ADD_BUTTON='//*[@id="addButton"]'
SAVE_BUTTON='//*[@id="DC_Device_Config_Save_Button"]'
#SELECT_CHECKBOX='//*[@id="existingProAssoTable"]/div[3]/div[1]/table/tbody/tr/td[1]'
SELECT_CHECKBOX_profile='//*[@id="existingProAssoTable"]/div[2]/div[1]/table/tbody/tr/td[1]/div'
XPATH_DELETE_CHECKBOX='//*[@id="headerCheckBox"]'
XPATH_DELETE_BUTTON='//*[@id="deleteBtn"]'
XPATH_ADD_BUTTON='//*[@id="addNewBtn"]'
XPATH_PROFILE_ASSOCIATIOn_BUTTON_CLICK='//*[@id="ProfileAssociation.ServiceArea"]/div[2]/div'
XPATH_CHOOSE_FILE='//*[@id="SS_FileUpload"]'
XPATH_CLICK_OK_BUTTON='//*[@id="DC_FileUpload_OkBtn"]'
XPATH_ORP_PARAM_SAVE_BUTTON = '//*[@id="DC_Device_Config_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP = '//*[contains(text(),"Saved successfully")]'
XPATH_Profile_value='//*[@id="DC_ProfileAssociation.ServiceArea_txt"]'
XPATH_Profile_DELETE_BUTTON='//*[@id="deleteBtn"]'

