
SELECT_VENUE_FILE='//span[contains(text(),"Venue File")]'
SELECT_ENTITYMAPPING_FILE='//span[contains(text(),"Entity Mapping File")]'
FOLDER_BUTTON='//*[@id="DMS_FOLDER_OPEN_DEBUG_ID"]'
UPLOAD_OK_BUTTON='//*[@id="NC_FileImport_Upload"]'
IMPORT_BUTTON='//*[@id="NC_FileImport_ImportButton"]'
OPERTION_HISTORY_BUTTON='//*[@id="NC_DMSHeader_Operation_History_Button"]'
OPERTION_HISTORY_RESOURCE_NAME='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[4]/div/div'
OPERTION_HISTORY_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[5]/div'
OPERTION_HISTORY_OPERATION_STATUS='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[6]/div/div'

XPATH_OH_RESOURCE_NAME='//div[@id="DMS_Operation_History_Table"]//div[2]//div//div//div[4]//input[1]'
XPATH_OH_OPERATION_TYPE='//div[@id="DMS_Operation_History_Table"]//div[2]//div//div//div[5]//input[1]'
ID_OH_APPLY_BUTTON='//*[@id="DC_OperationHistory_ApplyFilter_Button"]'

SHOW_ADVANCE_OPTION='//*[@id="showAdvanceBtn"]'
PRO_ASSOCIATION_INPUT='//*[@id="existingProAssoTable"]/div[2]/div/div/div[2]/input'
APPLY_FILTER='//*[@id="applyFilterBtn"]'
ADD_BUTTON='//*[@id="addButton"]'
SAVE_BUTTON='//*[@id="DC_Device_Config_Save_Button"]'
SELECT_CHECKBOX='//*[@id="existingProAssoTable"]/div[3]/div[1]/table/tbody/tr/td[1]'
XPATH_DELETE_CHECKBOX='//*[@id="headerCheckBox"]'
XPATH_DELETE_BUTTON='//*[@id="deleteBtn"]'
XPATH_ADD_BUTTON='//*[@id="addNewBtn"]'
XPATH_PROFILE_ASSOCIATIOn_BUTTON_CLICK='//*[@id="ProfileAssociation.ServiceArea"]/div[2]/div'
XPATH_CHOOSE_FILE='//*[@id="SS_FileUpload"]'
XPATH_CLICK_OK_BUTTON='//*[@id="DC_FileUpload_OkBtn"]'
XPATH_ORP_PARAM_SAVE_BUTTON = '//*[@id="DC_Device_Config_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP = '//*[contains(text(),"Saved successfully")]'

XPATH_DELTA_PARAM_ICON_BUTTON = '//*[@id="DC_Provision_Status_Count_HLayout"]/div[3]/div/a'
XPATH_DELTA_SEARCH_INPUT = '//*[@id="DC_Provisioning_Status_Table"]/div[2]/div/div/div[1]/input'
ID_PROVISIONING_APPLY_BUTTON = 'id=applyFilter'
#XPATH_PROVISIONING_X2C_NAME = '//*[@id="DC_Provisioning_Status_Table"]/div[3]/div[1]/table/tbody/tr/td[1]/div'
XPATH_PROVISIONING_X2C_NAME = '//div[contains(text(),"X2 C")]'
XPATH_CUUP_TOPOLOGY_LINK = '//*[@id="cuUserPlane"]/div/div[2]/div/div[1]/div/a'
XPATH_SUMMARY_VALUE = 'id=DC_SummaryOUIPC'
XPATH_DU_TOPOLOGY_LINK = '//*[@id="distributedUnit"]/div/div[2]/div/div[1]/div/a'
XPATH_CUCP_TOPOLOGY_LINK = '//*[@id="cuControlPlane"]/div/div[2]/div/div[1]/div/a'
XPATH_RP_TOPOLOGY_LINK = '//*[@id="DMS_DU_RP_totalServiceCountLayout"]/div[1]/div/a'
XPATH_RP_SUMMARY_VALUE = '//*[@id="DC_CONTENT_LAYOUT_FeatureHeadingLayout"]/div[1]/div/div[3]/div'



