XPATH_OWP_PROFASSO_PROFILE_ASSOCIATION = '//*[text()="Profile Association"]/parent::*/parent::*'
XPATH_OWP_PROFASSO_LOAD_SERVICE_SETTING_BUTTON='//div[@id="ProfileAssociation.ServiceArea"]//div[@role="button"]'
XPATH_OWP_PROFASSO_CHOOSE_FILE= '//input[@type="file"]'
XPATH_OWP_PROFASSO_ADD_NEW_PROFILE='id=addNewBtn'
ID_OWP_PROFASSO_DC_CONFIG = 'id=DC_Menu_configuration_ID'
ID_OWP_PROFASSO_PROF_ASSO = 'id=DC_Profile Association'
ID_OWP_PROFASSO_FILE_UPLOAD_OK_BUTTON = 'id=DC_FileUpload_OkBtn'
ID_OWP_PROFASSO_CONFIG_SAVE_BUTTON = '//button[@id="DC_Device_Config_Save_Button"]'
XPATH_OWP_CARRIER_AGGRE_BUTTON= '//div[@id="DC_Carrier Aggregation"]//div[contains(@class,"v-button")]'
XPATH_OWP_DOWNLINK_CA_VALUE = '//span[contains(text(),"{value}")]'
XPATH_OWP_FILTER_DROPDOWN_BUTTON= '//div[@class="v-filterselect-button"]'
ID_OWP_DEVICE_CONFIG_SAVE= '//*[@id="DC_Device_Config_Save_Button"]'
ID_OWP_OVERRIDDEN_PARAM_HEADER = 'id=DC_DMS Overridden Params_Header'
DEVICE_OVERWRRIDDEN_PARAMETER = '{dms_device_console}#!mv/configuration/?srchKey=MAC&id={device_macid}&dt=onecell&context=null'
XPATH_OWP_DOWNLINK_CA_VALUE_TO_GET = '//input[@class="v-filterselect-input"]'


XPATH_ORP_SECTOR_TAB = '//div[div[div[contains(text(), "{sector}")]]]'
XPATH_ORP_COLLAPSE_EXPAND_BUTTON = '//*[contains(text(), " All")]/parent::button'
XPATH_ORP_COLLAPSE_EXPAND_TEXT = '//*[@id="DC_ExpandCollapse"]/span'
ID_ORP_SEARCH_INPUT = 'id=DC_Search_TextField'
ID_ORP_SEARCH_BUTTON = 'id=DC_Search_Button'
XPATH_ORP_SCALAR_PARAM_INPUT = '//*[contains(text(), "{section}")]//ancestor::div[1]//following-sibling::div//*[contains(text(), "{overridden_param}")]/parent::div//input'
XPATH_ORP_TABULAR_PARAM_INPUT = '//*[contains(text(), "{section}")]//ancestor::div[1]//following-sibling::div//input[contains(@id, "{overridden_param}")]'
XPATH_ORP_PARAM_SAVE_BUTTON = '//*[@id="DC_Device_Config_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP = '//*[contains(text(),"Saved successfully")]'
XPATH_ORP_TABULAR_PARAM_ADD_LIST_BUTTON = '//*[contains(text(), "{section}")]//ancestor::div[1]//following-sibling::div//*[starts-with(@id, "DC_Add_New_")]'
XPATH_ORP_TABULAR_PARAM_DELETE_LIST_BUTTON = '//*[contains(text(), "{section}")]//ancestor::div[1]//following-sibling::div//*[@id="tabular-delete-layout"]'
#XPATH_ORP_SCALAR_PARAM_DELETE_BUTTON = '//*[contains(text(), "{section}")]//ancestor::div[1]//following-sibling::div//*[contains(text(), "{overridden_param}")]/following-sibling::div[@id="scalar-delete-layout"]'
XPATH_ORP_RP_WHITELIST='//textarea[@id="DC_WL_RP_Whitelist_Value_TextArea"]'
XPATH_ORP_RP_VERIFY_WHITELIST= '//span[contains(text(),"Verify Whitelist")]'
XPATH_ORP_RP_VERIFY_WHITELIST_SUCCESSFUL= '//div[text()="Verification successful!"]'
XPATH_ORP_RP_WHITELIST_EXPAND_BUTTON='//div[contains(@class,"v-button-v-disclosure-caption")]'
XPATH_ORP_WHITELIST_DELETE_PARAMS = '//button[@id="DC_WL_RP_Whitelist_Delete_button"]'
XPATH_ORP_RF_DOWNLINK_DELETE_BTN="//input[@id='DC_DLBandwidth_TF']/following-sibling::div/div"
XPATH_ORP_RF_UPLINK_DELETE_BTN="//input[@id='DC_ULBandwidth_TF']/following-sibling::div/div"
XPATH_ORP_ECSFB_MULTIPLENID_DELETE_BTN="//div[@id='DC_MultipleNid_Label']/following-sibling::div/div"
XPATH_ORP_ECSFB_MULTIPLESID_DELETE_BTN="//div[@id='DC_MultipleSid_Label']/following-sibling::div/div"
XPATH_ORP_ECSFB_HOMEREG_DELETE_BTN="//div[@id='DC_HomeReg_Label']/following-sibling::div/div"
XPATH_OWP_CARRIER_AGGRE_DELETE_BUTTON="//div[@id='DC_downlinkCaEnable_ComboBox']/following-sibling::div/div"

XPATH_TRIGGER_CONFIG_VALUE='//*[@id="DC_X2TriggeredPciReconfigAllowed_ComboBox"]/input'

XPATH_SECTOR_DELETE_BUTTON='//*[contains(@class,"decrement")]'
XPATH_SECTOR_ADD_BUTTON='//*[contains(@class,"increment")]'

XPATH_SECTOR_CELL_PARAMETER='//*[@id="DC_CellIdentity_TF"]'
XPATH_CELL_IDENTITY_COMBO='//*[@id="DC_CellIdentity_ComboBox"]/div'
XPATH_CELL_IDENTITY_VALUE='//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[1]/td'
XPATH_CONFIGURE_ACB_BUTTON='//*[@id="DC_ConfigBtn_1"]'
XPATH_CONFIGURE_ACB_OK_BUTTON='//*[@id="DC_Window_Ok_Button"]'
XAPTH_CONFIGURE_BARRING='//*[@id="DC_PLMN.BarringForEmergency_ComboBox"]'
XAPTH_BARRING_FACTOR='//*[@id="DC_PLMN.MODataBarringFactor_ComboBox"]'
XAPTH_BARRING_FACTOR_MO_INPUT='//*[@id="DC_PLMN.MODataBarringFactor_ComboBox"]/div'
XAPTH_BARRING_FACTOR_DROPBOX='//*[@id="DC_PLMN.BarringForEmergency_ComboBox"]/div'
XAPTH_BARRING_FACTOR_INPUT='//*[@id="DC_PLMN.BarringForEmergency_ComboBox"]/input'
#XAPTH_CONFIGURE_BARRING= '//div[@id="DC_PLMN.BarringForEmergency"]//div[contains(@class,"v-button")]'

XPATH_PROVISIONED_DATA_HEADER='//*[@id="DC_Provisioned Data_Header"]'
XPATH_PLMN_TABLE='//*[@id="Public Land Mobile Network (PLMN) List"]'
XAPTH_RF_PARAMETER='//*[@id="DC_RF Parameters Sector"]'
XPATH_SPS_TABLE='//*[@id="DC_SPS Parameters"]'

XPATH_FREQUENCY_BAND_INDICATOR='//*[@id="LteNeighborList.X_0005B9_FreqBandIndicatorPriority"]/div'
XPATH_FREQUENCY_BAND_VALUE_TRUE='//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[2]/td'
XPATH_FREQUENCY_BAND_VALUE_FALSE='//*[@id="VAADIN_COMBOBOX_OPTIONLIST"]/div/div[2]/table/tbody/tr[3]/td'


XPATH_BAND_RESERVATION_LABEL='//div[@id="dynamic_table_title_Label"][contains(text(),"Band Reservation")]'
XPATH_CELL_IDENTITY='//*[@id="DC_CellIdentity_Label"][contains(text(),"Cell Mode and Cell Identity")]'
XPATH_DOWNLINK_BANDWIDTH='//*[@id="DC_DLBandwidth_Label"][contains(text(),"Downlink Bandwidth")]'
XPATH_DOWNLINK_VALUE='//*[@id="DC_DLBandwidth_TF"]'
BAND_RESERVATION_VALUE='//*[@id="DC_SlotRes.PartNumber_1"]'
#XPATH_RESULT_PANEL='//div[contains(@class,"Devicehistory")]'
XPATH_ENODE_OPTIONAL_PARAM='//*[@id="DC_PnPStatus_Box_eNodeB Optional Delta Params"]'
XPATH_ENODE_OPTIONAL_PARAM_CONF_VALUE='//*[@id="DC_PnPStatus_Box_eNodeB Optional Conf Params"]'
XPATH_BLACKLIST_RADIO='//*[@id="DC_Grid_Table_Label_Display_Blacklisted Radio Units"][contains(text(),"Blacklisted Radio Units")]'
XPATH_BLACKLIST_TEXT='//*[@id="DC_Grid_Table_Label_Text_Blacklisted Radio Units"]'
XPATH_CATM1_TABLE='//*[@id="DC_CatM1 Sector"]'

XPATH_SECTOR1_OPTIONAL_PARAM='//*[@id="DC_PnPStatus_Box_Sector 1 Optional Delta Params"]/div[2]/div'
XPATH_SAVED_SPID_VALUE='//*[@id="DC_SPIDEnable_ComboBox"]/input'
XPATH_DELTA_PARAM_ICON='//*[@id="DC_CONTENT_LAYOUT_FeatureHeadingLayout"]/div[2]/div/div[1]/div/div[5]/div/a'
#XPATH_DELTA_SPID_VALUE='//*[@id="DC_ProvisionedDataTable_Table"]/div[2]/div[1]/table/tbody/tr/td[2]/div/div'
XPATH_DELTA_SEARCH_INPUT='//*[@id="DC_Provisioning_Status_Table"]/div[2]/div/div/div[1]/input'
ID_PROVISIONING_APPLY_BUTTON='id=applyFilter'
XPATH_PROVISIONING_SPID_VALUE='//div[contains(text(),"TRUE")]'
XPATH_PROVISIONING_SPID_SOURCE='//*[@id="DC_Provisioning_Status_Table"]/div[3]/div[1]/table/tbody/tr/td[6]/div/div/div'
XPATH_PROVISIONED_SPID_VALUE='//*[@id="DC_ProvisionedDataTable_Table"]/div[2]/div[1]/table/tbody/tr/td[2]/div/div'
XPATH_PROVISIONED_SPID_SOURCE='//*[@id="DC_ProvisionedDataTable_Table"]/div[2]/div[1]/table/tbody/tr/td[3]/div/div'
XPATH_SPID_PNP_PAGE='//*[@id="DC_Grid_Table_Label_Display_X_0005B9 SPID Enable"]'
XPATH_SPID_VALUE_PNP_PAGE='//*[@id="DC_Grid_Table_Label_Text_X_0005B9 SPID Enable"]'

XPATH_SAVED_MIMO_VALUE='//*[@id="DC_X_0005B9_Enable4X4MIMO_ComboBox"]/input'
XPATH_PROVISIONING_MIMO_VALUE='//*[@id="DC_Provisioning_Status_Table"]/div[3]/div[1]/table/tbody/tr/td[5]/div/div'
XPATH_PROVISIONING_MIMO_SOURCE='//*[@id="DC_Provisioning_Status_Table"]/div[3]/div[1]/table/tbody/tr/td[6]/div/div/div'
XPATH_PROVISIONED_MIMO_VALUE='//*[@id="DC_ProvisionedDataTable_Table"]/div[2]/div[1]/table/tbody/tr/td[2]/div/div'
XPATH_PROVISIONED_MIMO_SOURCE='//*[@id="DC_ProvisionedDataTable_Table"]/div[2]/div[1]/table/tbody/tr/td[3]/div/div'
XPATH_MIMO_PNP_STATUS='//div[@id="DC_Grid_Table_Label_Display_X_0005B9 Enable 4X4 MIMO"]'
XPATH_MIMO_VALUE_PNP_STATUS='//div[@id="DC_Grid_Table_Label_Text_X_0005B9 Enable 4X4 MIMO"]'

XPATH_DMS_OVERRIDEN_MENU = "//*[@id='DC_Menu_configuration_ID']/div[1]"
ID_DASHBOARD_DMSOVERRIDEN_SUMMARY ='id=DC_DMS Overridden Params_Header'
XPATH_DASHBOARD_DMSOVERRIDEN_GNBCONFIG = "//span[contains(text(),'gNB Configuration')]"

gName_value='//*[contains(@id,"gNBName_TF")]'

ID_CUCP_Notification='id=DC_PnPStatus_Box_Notification Subscription'
ID_CUCP_NOTIFICATION_PNP_STATUS='id=DC_Grid_Table_Label_Display_Mandatory Notifications Subscription'
ID_CUCP_NOTIFICATION_VALUE='id=DC_Grid_Table_Label_Text_Mandatory Notifications Subscription'
XPATH_NOTIFICATION_ROW='//div[contains(text(),"Mandatory Notification Computation")]'
XPATH_COMP_NEW_VALUE='//div[contains(text(),"x2c-state-info")]'
XPATH_COMP_CUUP_NEW_VALUE='//div[contains(text(),"e1-state-info")]'
XPATH_COMP_DU_NEW_VALUE='//div[contains(text(),"nrcell-state-info,nrcell-paraminuse-info,ru-notifi")]'
XPATH_X2C_ROW = '//div[contains(text(),"X2C TIA Value Change")]'
XPATH_X2C_IPADDRESS='//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[2]/td[1]/div'

XPATH_X2C_INTERFACE_VALUE = '//div[contains(text(),"eth1")]'
ID_GNB_PROVISIONED_DATA_HEADER = 'id=DC_Provisioned Data_Header'
XPATH_CUCP_X2C_PARAM ='//span[contains(text(),"X2 Configuration")]'
ID_PROVISIONING_X2C_SOURCE = 'id=static_table_source_Value_Label'
XPATH_PROVISIONING_X2CIP_VALUE = '//*[@id="DC_EPX2C_Table"]/div[2]/div[1]/table/tbody/tr/td[2]/div/div'
XPATH_EPX2C_ROW = '//div[contains(text(),"Netconf EPX2_C Computation")]'
XPATH_EPX2C_IP_VALUE = '//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[3]/td[3]/div/div'

XAPTH_VES_PROVISIONED_DATA_Heartbeat = "//div[@id='DC_Heartbeat Configuration']"
#Heartbeat_Interval = "//div[contains(text(),'Heartbeat Period (minutes)')]"
Heartbeat_Interval='Heartbeat Period (minutes)'
Heartbeat_Interval_Value = '10'
Xpath_gNB_Dashboard = 'id=DC_Menu_Content_Dashboard_Button'
Heartbeat_Interval_Value_dashboard ='id=DC_HeartBeatInterval_Value_Label'
heartbeat_value_provisioned_data='//*[@id="DC_ProvisionedDataTable_Table"]/div[2]/div[1]/table/tbody/tr/td[2]'

XPATH_GUIOVERRIDE_DELETE_BUTTON='//*[@id="scalar-delete-layout-label"]'
XPATH_DC_gNBId_TF='//input[@id="DC_gNBId_TF"]'
XPATH_DC_CUUP_gNBId_TF='//input[@id="DC_CUUP_gNBId_TF"]'
ID_LOAD_PROVISIONED_DATA='//*[@id="loadProvisionedData"]'
XPATH_DC_NRCell_LocalId_TF = '//input[@id="DC_NRCell_LocalId_TF"]'

XPATH_DMS_Entity_Mapping_OVERRIDEN_MENU = '//*[@id="DC_Menu_entitymappingparams_ID"]/div[1]'
XPATH_DMS_OTHER_OVERRIDEN_MENU = '//*[@id="DC_Menu_otherOvrParams_ID"]/div[1]'
ID_Entity_Mapping_OVERRIDDEN_PARAM_HEADER = '//*[@id="DC_Entity Mapping Overridden Params_Header"]'
#XPATH_DU_CELL1_TAB = '//div[contains(text(),"Cell 1")]'
#XPATH_DU_CELL4_TAB = '//div[contains(text(),"Cell 4")]'
XPATH_DU_CELL1_TAB = '//*[@id="gwt-uid-26"]/div'
XPATH_DU_CELL4_TAB = '//*[@id="gwt-uid-29"]/div'
XPATH_DC_cellLocalId_TF='//input[@id="DC_cellLocalId_TF"]'
XPATH_DC_nRPCI_TF= '//input[@id="DC_nRPCI_TF"]'
XPATH_DC_RSI_TF = '//input[@id="DC_RSI_TF"]'
XPATH_DC_nRFreqBandDL_TF = '//input[@id="DC_nRFreqBandDL_TF"]'
XPATH_DC_bSChanBwUL_TF= '//input[@id="DC_bSChanBwUL_TF"]'
XPATH_DC_bSChanBwDL_TF = '//input[@id="DC_bSChanBwDL_TF"]'
XPATH_DC_arfcnUL_TF = '//input[@id="DC_arfcnUL_TF"]'
XPATH_DC_arfcnDL_TF = '//input[@id="DC_arfcnDL_TF"]'
Whitelist_cell1_text_area='//*[@id="DC_WL_RP_Whitelist_Value_TextArea_1"]'
XPATH_Whitelist_provisioned_table='//*[@id="X0005B9_whitelist"]'

XPATH_HBPeriod_EnterCP ='//input[@id="DC_cucp_hbPeriod_TF"]'
XPATH_GNBNameCP = '//input[@id="DC_cucp_gNBName_TF"]'
XPATH_HBPeriod_EnterUP = '//input[@id="DC_cuup_hbPeriod_TF"]'
XPATH_GNBNameUP = '//input[@id="DC_cuup_gNBName_TF"]'
XPATH_GNBNameDU = '//input[@id="DC_gNBName_TF"]'
XPATH_HBPeriod_EnterDU = '//input[@id="DC_du_hbPeriod_TF"]'
XPATH_OVEERIDE_SAVE_BUTTON = '//span[contains(text(),"Save")]'
XPATH_PNP_STATUS_BOX = '//*[@id="DC_PnPStatus_Box_Provision Delta Feature Conf"]/div[2]/div'
XPATH_PNP_REPORT_TEXT = '//*[@id="DC_PnpStatus_PnpReport_Provision Delta Feature Conf"]/div/div/div[2]/div/div/div/div[1]/div'
XPATH_FAILURE_REASON = '//*[@id="DC_PnpStatus_PnpReport_Provision Delta Feature Conf"]/div/div/div[2]/div/div/div/div[2]/div'
XPATH_HBPeriod_DETAILS = '//*[@id="DC_PnpStatus_PnpReport_Provision Delta Feature Conf"]/div/div/div[2]/div/div/div/div[3]/div'
XPATH_GNBNAME_DETAILS = '//*[@id="DC_PnpStatus_PnpReport_Provision Delta Feature Conf"]/div/div/div[2]/div/div/div/div[4]/div'
XPATH_PROVISIONED_DATA = '//*[@id="DC_ProvisionedDataTable_Table"]/div[2]/div[1]/table/tbody/tr[2]'
XPATH_PROVISIONED_HBPeriod = '//*[@id="DC_ProvisionedDataTable_Table"]/div[2]'
XPATH_HISTORY_PROVISIONING1 = '//*[@id="resultPanel"]/div[3]/div/div/div[1]/div/div[2]/div[1]/table/tbody/tr[7]/td[3]/div'
XPATH_HISTORY_PROVISIONING2 = '//*[@id="resultPanel"]/div[3]/div/div/div[1]/div/div[2]/div[1]/table/tbody/tr[9]/td[3]/div'
XPATH_HISTORY_UPPROVISIONING1='//*[@id="resultPanel"]/div[3]/div/div/div[1]/div/div[2]/div[1]/table/tbody/tr[6]/td[3]/div'
XPATH_PROVISIONINGHB_DU = '//tbody/tr[7]/td[3]/div[1]'
XPATH_PROVISIONINGgNB_DU = '//tbody/tr[9]/td[3]'
XPATH_HISTORY_UPPROVISIONING2='//*[@id="resultPanel"]/div[3]/div/div/div[1]/div/div[2]/div[1]/table/tbody/tr[8]/td[3]/div'
#XPATH_HISTORY_DUPROVISIONING = '//*[@id="resultPanel"]/div[3]/div/div/div[1]/div/div[2]/div[1]/table/tbody/tr[8]/td[3]/div'
XPATH_HISTORY_DU_HB_PROVISIONING = '//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[1]/td[4]/div/div'
#XPATH_HISTORY_DU_HB_PROVISIONING = '//*[@id="resultPanel"]/div[3]/div/div/div[1]/div/div[2]/div[1]/table/tbody/tr[6]/td[3]/div'
#XPATH_HISTORY_DU_gNBNAME = '//*[@id="resultPanel"]/div[3]/div/div/div[1]/div/div[2]/div[1]/table/tbody/tr[8]/td[3]/div'
XPATH_HISTORY_DU_gNBNAME = '//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[3]/td[4]'
XPATH_NEW_gNBNAME_VALUE = '//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[3]/td[3]/div/div'
XPATH_NEW_HBP_VALUE = '//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[1]/td[3]/div/div'
XPATH_NEW_HBP_UP = '//*[@id="DC_DHDetails_Window_Content"]/div/div/div/div[2]/div/div/div/div[2]/div[1]/table/tbody/tr[1]/td[3]/div/div'
#XPATH_CLOSE_BUTTON = '//*[@id="2020_window_close"]'
XPATH_CLOSE_BUTTON= '//*[@id="DC_DHDetails_Window"]/div/div/div/div[2]'
XPATH_SAVE = '//button[@id="DC_Device_Config_Save_Button"]'



XPATH_PROVISIONING_VALUE = '//*[@id="DC_Provisioning_Status_Table"]/div[2]/div[1]/table/tbody/tr/td[4]/div/div'
XPATH_DELTA_PARAM_ICON_BUTTON = '//*[@id="DC_Provision_Status_Count_HLayout"]/div[3]/div/a'
#XPATH_DELTA_SEARCH_INPUT = '//*[@id="DC_Provisioning_Status_Table"]/div[2]/div/div/div[1]/input'
#XPATH_DELTA_SEARCH_INPUT='//*[@id="DC_Provisioning_Status_Table"]/div[1]/div[1]/div/table/tbody/tr[2]/td[1]/div/input'

ID_PROVISIONING_APPLY_BUTTON = 'id=applyFilter'
#XPATH_PROVISIONING_X2C_NAME = '//*[@id="DC_Provisioning_Status_Table"]/div[3]/div[1]/table/tbody/tr/td[1]/div'
#XPATH_PROVISIONING_X2C_NAME = '//div[contains(text(),"X2 C")]'
XPATH_PROVISIONING_X2C_NAME = '//*[@id="DC_Provisioning_Status_Table"]/div[2]/div[1]/table/tbody/tr/td[1]/div'
XPATH_CUUP_TOPOLOGY_LINK = '//*[@id="cuUserPlane"]/div/div[2]/div/div[1]/div/a'
XPATH_SUMMARY_VALUE = 'id=DC_SummaryOUIPC'
XPATH_DU_TOPOLOGY_LINK = '//*[@id="distributedUnit"]/div/div[2]/div/div[1]/div/a'
XPATH_CUCP_TOPOLOGY_LINK = '//*[@id="cuControlPlane"]/div/div[2]/div/div[1]/div/a'
XPATH_RP_TOPOLOGY_LINK = '//*[@id="DMS_DU_RP_totalServiceCountLayout"]/div[1]/div/a'
XPATH_RP_SUMMARY_VALUE = '//*[@id="DC_CONTENT_LAYOUT_FeatureHeadingLayout"]/div[1]/div/div[3]/div'
XPATH_DELTA_ICON = '//*[@id="DC_CONTENT_LAYOUT_FeatureHeadingLayout"]/div[2]/div/div/div/div[5]/div/a'
XPATH_PROVISIONING_SGW_NAME = '//*[@id="DC_Provisioning_Status_Table"]/div[2]/div[1]/table/tbody/tr[2]/td[1]/div'
XPATH_PROVISIONING_SGW_VALUE='//*[@id="DC_Provisioning_Status_Table"]/div[2]/div[1]/table/tbody/tr[2]/td[4]/div/div'


#Entity

SELECT_VENUE_FILE='//span[contains(text(),"Venue File")]'
SELECT_ENTITYMAPPING_FILE='//span[contains(text(),"Entity Mapping File")]'
FOLDER_BUTTON='//*[@id="DMS_FOLDER_OPEN_DEBUG_ID"]'
UPLOAD_OK_BUTTON='//*[@id="NC_FileImport_Upload"]'
IMPORT_BUTTON='//*[@id="NC_FileImport_ImportButton"]'
OPERTION_HISTORY_BUTTON='//*[@id="NC_DMSHeader_Operation_History_Button"]'
OPERTION_HISTORY_RESOURCE_NAME='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[4]/div/div'
OPERTION_HISTORY_OPERATION_TYPE='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[5]/div'
OPERTION_HISTORY_OPERATION_STATUS='//*[@id="DMS_Operation_History_Table"]/div[3]/div[1]/table/tbody/tr[1]/td[6]/div/div'

XPATH_OH_RESOURCE_NAME='//div[@id="DMS_Operation_History_Table"]//div[2]//div//div//div[4]//input[1]'
XPATH_OH_OPERATION_TYPE='//div[@id="DMS_Operation_History_Table"]//div[2]//div//div//div[5]//input[1]'
ID_OH_APPLY_BUTTON='//*[@id="DC_OperationHistory_ApplyFilter_Button"]'

SHOW_ADVANCE_OPTION='//*[@id="showAdvanceBtn"]'
PRO_ASSOCIATION_INPUT='//*[@id="existingProAssoTable"]/div[2]/div/div/div[2]/input'
APPLY_FILTER='//*[@id="applyFilterBtn"]'
ADD_BUTTON='//*[@id="addButton"]'
SAVE_BUTTON='//*[@id="DC_Device_Config_Save_Button"]'
SELECT_CHECKBOX='//*[@id="existingProAssoTable"]/div[3]/div[1]/table/tbody/tr/td[1]'
XPATH_DELETE_CHECKBOX='//*[@id="headerCheckBox"]'
XPATH_DELETE_BUTTON='//*[@id="deleteBtn"]'
XPATH_ADD_BUTTON='//*[@id="addNewBtn"]'
XPATH_PROFILE_ASSOCIATIOn_BUTTON_CLICK='//*[@id="ProfileAssociation.ServiceArea"]/div[2]/div'
XPATH_CHOOSE_FILE='//*[@id="SS_FileUpload"]'
XPATH_CLICK_OK_BUTTON='//*[@id="DC_FileUpload_OkBtn"]'
XPATH_ORP_PARAM_SAVE_BUTTON = '//*[@id="DC_Device_Config_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP = '//*[contains(text(),"Saved successfully")]'

XPATH_DELTA_PARAM_ICON_BUTTON = '//*[@id="DC_Provision_Status_Count_HLayout"]/div[3]/div/a'
XPATH_DELTA_SEARCH_INPUT = '//*[@id="DC_Provisioning_Status_Table"]/div[2]/div/div/div[1]/input'
ID_PROVISIONING_APPLY_BUTTON = 'id=applyFilter'
#XPATH_PROVISIONING_X2C_NAME = '//*[@id="DC_Provisioning_Status_Table"]/div[3]/div[1]/table/tbody/tr/td[1]/div'
XPATH_PROVISIONING_X2C_NAME = '//div[contains(text(),"X2 C")]'
XPATH_CUUP_TOPOLOGY_LINK = '//*[@id="cuUserPlane"]/div/div[2]/div/div[1]/div/a'
XPATH_SUMMARY_VALUE = 'id=DC_SummaryOUIPC'
XPATH_DU_TOPOLOGY_LINK = '//*[@id="distributedUnit"]/div/div[2]/div/div[1]/div/a'
XPATH_CUCP_TOPOLOGY_LINK = '//*[@id="cuControlPlane"]/div/div[2]/div/div[1]/div/a'
XPATH_RP_TOPOLOGY_LINK = '//*[@id="DMS_DU_RP_totalServiceCountLayout"]/div[1]/div/a'
XPATH_RP_SUMMARY_VALUE = '//*[@id="DC_CONTENT_LAYOUT_FeatureHeadingLayout"]/div[1]/div/div[3]/div'


XPATH_ORP_PARAM_SAVE_BUTTON = '//*[@id="DC_Device_Config_Save_Button"]'
XPATH_DELETE_WHITELIST_BUTTON='//*[@id="RP_Whitelist_Vlyout"]/div[1]/div/button'
XPATH_PROVISION_VALUE_WHITELIST='//*[@id="DC_X0005B9_whitelist_Table"]/div[2]/div[1]/div[2]'
XPATH_CUREPLAY_NOTIFICATION_ROW='//div[contains(text(),"X2C State Notification")]'
XPATH_UPREPLAY_NOTIFICATION_ROW='//div[contains(text(),"E1 State Notification")]'
XPATH_DUREPLAY_NOTIFICATION_ROW='//div[contains(text(),"RP State Notification")]'
XPATH_HISTORY_DETAIL_CLOSE='//*[@id="DC_DHDetails_Window"]/div/div/div/div[2]'


XPATH_ORP_gNB_RP_WHITELIST='//*[@id="DC_WL_RP_Whitelist_Value_TextArea_1"]'
XPATH_ORP_RP_SHOW_ADVANCE_OPTIONS ='//*[@id="DC_WL_Link_Show_Advanced"]/div/div/div'
XPATH_ORP_gNB_CELL4_RP_WHITELIST='//*[@id="RP_Whitelist_Vlyout"]/div[4]/div/div'
ID_DU_WHITELIST_UNKNOWN_RP_WARNING = '//*[@id="DC_WhiteList RPs"]'
XPATH_ORP_RP_VERIFY_WHITELIST_WARNING ='//div[contains(text(),"DMS has no knowledge of some of the RPs")]'
XPATH_ORP_PARAM_CANCEL_BUTTON = '//*[@id="DC_Device_Config_Cancel_Button"]/span'

XPATH_VES_param_1='(//*[@id="scalar-delete-layout-label"])[1]'
XPATH_VES_param_2='(//*[@id="scalar-delete-layout-label"])[2]'
XPATH_VES_param_3='(//*[@id="scalar-delete-layout-label"])[3]'
XPATH_ORP_PARAM_SAVE_BUTTON_gNB = '//*[@id="DC_Device_Config_Save_Button"]'
XPATH_ORP_SAVE_NOTIFICATION_POPUP_gNB = '//*[contains(text(),"Saved successfully")]'
XPATH_VES_URL_DMS='(//div[contains(text(),"")]/input)[2]'
XPATH_VES_USERNAME_DMS='(//div[contains(text(),"")]/input)[3]'
XPATH_VES_PASSWORD_DMS='(//div[contains(text(),"")]/input)[4]'

XPATH_DMS_FLAG_BOX_PNP='//*[@id="DC_PnPStatus_Box_DMS Flag For CU-CP Activation"]'
XPATH_FLAG_TEXT='//*[@id="DC_PnpStatus_PnpReport_DMS Flag For CU-CP Activation"]/div/div/div[2]'
XPATH_LAST_ESTABLISHED='//*[@id="DC_LastEstSessTime_Value_Label"]'
url_ves_DMS_value1='http://10.211.1.11:7001/eventListener/v21'
Username_ves_DMS_value1='admin123'
Password_ves_DMS_value1='admin1234'
XAPTH_VES_PROVISIONED_DATA_DMSGUI_table='//*[@id="DC_VES Collector Configuration"]'

XPATH_SERVER_TIME='//*[@id="DC_ServerTime_Layout"]'

XPATH_gNBIDLength = '//*[@id="DC_gNBIdLength_TF"]'
XPATH_SAVED = '//*[@id="CONTENT_LAYOUT"]/div/div[3]/div[1]/div/div/div/div'
XPATH_PENDING_PROVISIONING = '//*[@id="DC_PendingProvisioningStatus"]'
XPATH_gNBIDLength_UP = '//*[@id="DC_CUUP_gNBIdLength_TF"]'
XPATH_DELETE_gNBIDLENTGH = '//*[@id="scalar-delete-layout-label"]'
#ID_ENTITY_MAPPING_HEADER = '//div[@id="DC_Entity Mapping Overridden Params_Header"]'
ID_ENTITY_MAPPING_HEADER = 'id=DC_Entity Mapping Overridden Params_Header'
#//div[@id='DC_Entity Mapping Overridden Params_Header']

#ENTITY_MAPPING_URL = '{dms_device_console}#!mv/entitymappingparams/?srchKey={device_macid}&dt=ONECELL5GCU&context=null'
DEVICE_ENTITY_MAPPING_URL_CU ='{dms_device_console}#!mv/entitymappingparams/?srchKey=MAC&id={device_macid}&dt=ONECELL5GCU&context=null'
DEVICE_ENTITY_MAPPING_URL_DU ='{dms_device_console}#!mv/entitymappingparams/?srchKey=MAC&id={device_macid}&dt=ONECELL5GDU&context=null'
XPATH_PLUS_ENTITY = '//*[@id="DC_Add_New_EPX2C_Button"]'
XPATH_ENTER_ENBID = '//*[@id="EPX2C.id"]'
XPATH_ENTER_IPADRESS = '//*[@id="EPX2C.remoteAddr"]'
XPATH_SAVE_ENTITY = '//*[@id="DC_Device_Config_Save_Button"]/span'
#XPATH_SAVE_ENTTIY = '//*[@id="DC_Device_Config_Save_Button"]/span'
XPATH_ENTITY_PNP_BOX = '//*[@id="DC_PnPStatus_Box_Provision Delta Min Mandatory Conf"]/div[2]/div'
XPATH_PROVISION_PNP_BOX_1 = '//*[@id="DC_PnpStatus_PnpReport_Provision Delta Min Mandatory Conf"]/div/div'
XPATH_DELETE_ENTITY = '//*[@id="DC_Action_Delete_Button"]/div'
